### PR TITLE
Update DockerHub overview programmatically

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@consideRatio @manics @minrk
It is now possible to update the DockerHub description(s) from the source code programmatically.
https://github.com/docker/hub-feedback/issues/2127

There is also an excellent action to make it easy for you: https://github.com/christian-korneck/update-container-description-action

**Review by consideRatio — APPROVED** [review]
Now it updates all overviews, but previously only updated base-notebook's overview? LGTM

**Comment by mathbunnyru** [comment]
> Now it updates all overviews, but previously only updated base-notebook's overview? LGTM

No, previously it didn't work at all and I've just enabled it an hour ago to make sure it works.
https://github.com/jupyter/docker-stacks/commit/257e44df817558ad32923805cfd937f48a3dfa2b

**Comment by mathbunnyru** [comment]
I've used existing descriptions and didn't update them, but I think they will have to be updated to reflect current state.

**Pull request merged**
