### PR TITLE
Fix conda hook to work in both terminal and Jupyter Notebook

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Describe your changes

This makes conda env activate correctly for the whole process, not just the terminals.
I think it is reasonable and desirable to have the same environment inside a terminal and a Jupyter Notebook.

## Issue ticket if applicable

Fix: https://github.com/jupyter/docker-stacks/issues/2043
Fix: https://github.com/jupyter/docker-stacks/issues/1792

## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
I tested it this way:

```
make build/docker-stacks-foundation
make build/base-notebook
docker run -it --rm -p 8888:8888 quay.io/jupyter/base-notebook
```

In both the terminal and inside Jupyter notebook the result is the same:
```
env | grep CONDA
CONDA_EXE=/opt/conda/bin/conda
CONDA_PREFIX=/opt/conda
CONDA_PROMPT_MODIFIER=(base) 
_CE_CONDA=
CONDA_SHLVL=1
CONDA_DIR=/opt/conda
CONDA_PYTHON_EXE=/opt/conda/bin/python
CONDA_DEFAULT_ENV=base
```

**Comment by mathbunnyru** [comment]
But this actually creates another problem:
`eval "$(conda shell.bash hook)"` sets PS1, and creates inline bash functions to make `conda activate` and `conda deactivate` work.

But people open new Jupyter Terminals in the Web UI, meaning these inline bash functions are lost.
PS1 is also lost, because `.bashrc` and some other files in Linux contain setting PS1.
It also means in the terminal `conda activate` and `conda deactivate` won't work at all in a Jupyter Terminal.
It's not nice at all.

This practically means that we will have to `eval` twice:
1. in a sourced magical file (which this PR added) - it will activate `base` environment, set proper env variables for the process
2. In the `.bashrc` - this will fix PS1 and add an ability to use `conda (de)activate` in Jupyter Terminals

**Comment by mathbunnyru** [comment]
I have no idea what's going on with the test here.
Moreover, it works funder under aarch64, so I can't even test it easily 😢

**Comment by mathbunnyru** [comment]
Also tested the recipe: `docker build -t test . -f custom_environment.dockerfile`, seems to work well.
PS1 now is also correct.

**Comment by mathbunnyru** [comment]
> @mathbunnyru I think the issue can be considered resolved as soon as
> 
> 1. the conda environment is activated for both JupyterLab (Terminal) and Jupyter Notebooks.
> 2. env variables are identical for IPython (started from JupyterLab Terminal) and Jupyter Notebooks.
>    
>    * This might not be the case for Terminal related env variables, though.
> 
> P.S.: I have added an order of precedence (i.e. numbering) for startup hooks: [b-data/jupyterlab-python-docker-stack@82da8b4](https://github.com/b-data/jupyterlab-python-docker-stack/commit/82da8b437d361987e8915ae92d6e341e045bbd77) ℹ️ Useful, if someone builds on the Jupyter Docker Stacks and wants to add additional startup hooks.

As a developer, I would like to agree - it seems to work, easy to implement and to change for a custom environment.
From a user perspective, I would like to be able to do `conda (de)activate` easily in terminal.
And having correct PS1 would be nice as well.

**Comment by mathbunnyru** [comment]
> Is it really a good idea that the custom environment is activated by default?

I think I can comment this code with some information.

**Comment by mathbunnyru** [comment]
> > `docker run -it --rm -p 8888:8888 --user root -e NB_USER=vicente test` works for me with a new recipe, so I think we can close the issue you mention.
> 
> Please check `import os; os.environ` and `import sys; sys.version` for both Notebook/Console 'Python 3 (ipykernel)' and 'python310'.
> 
> Is this expected?

I checked with commented activation (as it is now in the PR).

`os.environ` results are the same (except JPY_SESSION_NAME).
I think Jupyter Lab/Console doesn't change conda when it is launched, so the variables are all the same

`sys.version` - `3.11.6` in default Notebook/Console and `3.10.13` in `python310`.
Totally fine

```
from typing import Self
```
This snippet works for default Notebook/Console and doesn't work for py310 versions (and it shouldn't work).

I also checked that python3.11 packages are not leaking somehow to `python310` - also works fine, `alembic` is available in default Notebook/Console and is not available in `python310`.

**Comment by benz0li** [comment]
> Totally fine

All fine; Agreed.

> I think Jupyter Lab/Console doesn't change conda when it is launched, so the variables are all the same

Yes. And the Jupyter Docker Stacks project is not supposed to fix IPython.

---

But I am quite sure people will complain that the custom (conda) environment is not activated when running the Notebook/Console with its kernel.

**Comment by mathbunnyru** [comment]
Nice, thanks for your help ❤️
I appreciate it.

I'll merge this when the tests pass.

**Pull request merged**
