### PR TITLE
Spark 3.0.1 -> fixes #1156

### LINKED ISSUE #1156: Pyspark-notebook  returned a non-zero code: 8
I cannot build pyspark-notebook docker image. It's give me below error
 **### returned a non-zero code: 8**

Help me pls.

```
Setting up openjdk-11-jre-headless:amd64 (11.0.8+10-0ubuntu1~20.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jfr to provide /usr/bin/jfr (jfr) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Removing intermediate container 92b51a1081ff
 ---> 53d289e797e6
Step 13/22 : WORKDIR /tmp
 ---> Running in 0b43654a1cbb
Removing intermediate container 0b43654a1cbb
 ---> e76a32080d84
Step 14/22 : RUN wget -q $(wget -qO- https://www.apache.org/dyn/closer.lua/spark/spark-${APACHE_SPARK_VERSION}/spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz\?as_json |     python -c "import sys, json; content=json.
load(sys.stdin); print(content['preferred']+content['path_info'])") &&     echo "${spark_checksum} *spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" | sha512sum -c - &&     tar xzf "spark-${APACHE_SPARK_VERSION}-bin-
hadoop${HADOOP_VERSION}.tgz" -C /usr/local --owner root --group root --no-same-owner &&     rm "spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz"
 ---> Running in 83519295cc25
The command '/bin/bash -o pipefail -c wget -q $(wget -qO- https://www.apache.org/dyn/closer.lua/spark/spark-${APACHE_SPARK_VERSION}/spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz\?as_json |     python -c "import sys
root@unkbot:~/test-jpi/docker-stacks/pyspark-notebook# eferred']+content['path_info'])") &&     echo "${spark_checksum} *spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" | sha512sum -c - &&     tar xzf "spark-${APACH
E_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" -C /usr/local --owner root --group root --no-same-owner &&     rm "spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz"' returned a non-zero code: 8

```

### PR DESCRIPTION
**Pull request by romainx**
Hello,

Upgrade to Spark `3.0.1` in order to fix #1156.
The build is working only while the version of Spark used in the image is available on the [Spark download page](https://spark.apache.org/downloads.html). In this case Spark `3.0.0` was no more available.

Best.

### CODE REVIEW

**Comment by romainx** [comment]
Changed `""` into `''` to pass an empty token. Seems to be linked to this warning:
```
/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py:2195: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use '' instead of "''" – or use CUnicode.
```

Added debug information (ouput of the command line).

**Comment by romainx** [comment]
@parente I would like to merge this PR because besides fixing the Spark build issue, it fixes a test that will cause all builds to fail.

**Comment by parente** [comment]
@romainx Thanks for the update. In the future, feel free to merge PRs that fix broken builds without my approval. 👍

**Comment by romainx** [comment]
@parente thank you. I will do that next time 😄

**Pull request merged**
