### PR TITLE
Show tags for third-party github actions

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@consideRatio @manics @minrk there is a brand new feature, which allows to specify tag in comments and these comments will be updated by `dependabot` as well!
This makes it both secure (when using tags) and human-readable.

https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/

**Comment by mathbunnyru** [comment]
I merged this one, created PR so I could mention you and let you know about this nice feature.

**Comment by consideRatio** [comment]
Nice improvement, thanks for sharing @mathbunnyru!

**Comment by mathbunnyru** [comment]
Today you willl see two more improvements like this. Hope you don't mind. I think they will be useful in other repos as well and I don't know a better way to share these cool things.

**Pull request merged**
