### PR TITLE
Error and fail start.sh on misconfiguration

### PR DESCRIPTION
**Pull request by mathbunnyru**
Fix: https://github.com/jupyter/docker-stacks/issues/1517

### CODE REVIEW

**Comment by mathbunnyru** [comment]
I want to know your opinion and also need to fix the tests.

**Review by consideRatio — COMMENTED** [review]
Hmmm you make the log function exit on error. I'm not so fond of making its purpose be expanded to that while still being named just `_log`.

I think I'd favor being explicit and including multiple `exit` codes. One could also consider having separate non-zero exit codes for the errors when exiting to allow users recognize an error via the exit code as well.

**Comment by mathbunnyru** [comment]
Thanks for your suggestion, I will fix this.
In general, do you agree with exiting on errors like these?

**Comment by consideRatio** [comment]
Hmmm... I think so, but I'm not that confident about it.

Do we have default values for the environment variables etc that can cause trouble, forcing someone to explicitly configure something to avoid errors? That would be a signal to me that we have been too strict.

**Comment by mathbunnyru** [comment]
I think the defaults are good, but I think there are many cases, where user sets one variable and forgets about another one (like chaning username requires `--user root`).
In cases like this the behavior is not clear.
The user gets a warning, but I beleive no one reads warnings until "it somehow works".

**Comment by mathbunnyru** [comment]
Closing this one, I don't think I'm gonna have enough time in the nearest future to finish this PR.

**Pull request closed without merging**
