### PR TITLE
Start using Ubuntu 20.04 (focal)

### PR DESCRIPTION
**Pull request by mathbunnyru**
Addresses https://github.com/jupyter/docker-stacks/issues/1089

### CODE REVIEW

**Comment by mathbunnyru** [comment]
jupyter/base-notebook:latest
u18: 649MB
u20: 664MB

jupyter/minimal-notebook:latest
u18: 2.51GB
u20: 2.96GB

Successfully tagged jupyter/r-notebook:latest
u18: 3.53GB
u20: 3.99GB

Successfully tagged jupyter/scipy-notebook:latest
u18: 3.41GB
u20: 3.93GB

Successfully tagged jupyter/tensorflow-notebook:latest
u18: 4.98GB
u20: 5.5GB

Successfully tagged jupyter/datascience-notebook:latest
u18: 4.76GB
u20: 5.28GB

Successfully tagged jupyter/pyspark-notebook:latest
u18 4.21GB
u20: 4.73GB

Successfully tagged jupyter/all-spark-notebook:latest
u18: 5.02GB
u20: 5.54GB

So this means an increase around 50 MB.
Most of the increase comes from minimal-notebook (+30 MB to the previous difference).

**Comment by romainx** [comment]
@mathbunnyru thank you sounds good!
I dot not know if we should make this move now (I have no opinion)?
Maybe one of the drawback could be to break something in the extensions / customization made by users on top of these stacks. However it must be done one day.

**Comment by parente** [comment]
We updated from 16.04 to 18.04 without much ceremony last time https://github.com/jupyter/docker-stacks/pull/641.

We might consider adding the `/etc/lsb_release` version info as a docker image tags going forward. I think we should at least manually tag the last build of each image on docker hub with `ubuntu-18.04` before merging this PR.

**Comment by mathbunnyru** [comment]
@parente so, do you want me to add this tagging in another PR or will you do it yourself?

**Comment by parente** [comment]
@mathbunnyru Apologies. I was looking to see if you and @romainx  agree with either approach first. 

If you do agree, I can manually tag the last 18.04 images sometime this week before merging this PR and open an issue to automate that tagging for anyone that wants to work on it.

**Comment by mathbunnyru** [comment]
> @mathbunnyru Apologies. I was looking to see if you and @romainx agree with either approach first.
> 
> If you do agree, I can manually tag the last 18.04 images sometime this week before merging this PR and open an issue to automate that tagging for anyone that wants to work on it.

Seems fine by me 👍

**Comment by romainx** [comment]
@mathbunnyru @parente sounds good for me also 👍

**Comment by parente** [comment]
I add tag `ubuntu-18.04` to the images already tagged `dd2087c75645` which are the current latest. Merging this PR now.

**Pull request merged**
