### PR TITLE
Webhook to update docker builds page

### PR DESCRIPTION
**Pull request by parente**
Addresses #113 in a different fashion. Updates the https://github.com/jupyter/docker-stacks/wiki/Docker-build-history page every time a new build tag is pushed to Docker Hub.

Webhook service is implemented in a notebook and turned into an API using jupyter_kernel_gateway for Friday fun.

Not ready to merge yet. I'd like to ensure the copy I've pushed to https://docker-stacks-webhook.mybluemix.net works a few times first. It doesn't have to run here: it can run anywhere kernel gateway can. It was just easiest for me.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Heh, this is neat Friday fun! Will you be writing a blog post somewhere?

**Comment by rgbkrk** [comment]
Nice notebook too.

**Comment by parente** [comment]
Worked fine on the last build. I'll update the README to point to the builds page before this goes in.

**Comment by parente** [comment]
All set. If we can't find a way to automate the builds using Circle CI or another hosted service, we can do something similar to this on the build VM we're already using.

**Pull request merged**
