### PR TITLE
Do not install python-dev

### PR DESCRIPTION
**Pull request by mathbunnyru**
It's an attempt to fix https://github.com/jupyter/docker-stacks/issues/1083
If everything builds fine, then we probably don't need to install python-dev manually.

### CODE REVIEW

**Comment by mathbunnyru** [comment]
jovyan@5daef95157f2:~$ apt-cache depends inkscape | grep python
  Depends: <python2:any>
    python2

It seems that inkscape depends on python2, but still, if we don't need something to be installed as a direct package, then let's not install it.

There is an inkscape bug, that it still needs python2, but it won't be fixed in 20.04. But as soon as 22.04 gets released, the size image will automatically shrink (https://bugs.launchpad.net/ubuntu/+source/inkscape/+bug/1735363)
Or we might delete inkscape.
Or we might use https://launchpad.net/~inkscape.dev/+archive/ubuntu/stable?field.series_filter=focal

**Comment by mathbunnyru** [comment]
@romainx @parente could you please take a look?

**Comment by romainx** [comment]
@mathbunnyru sorry for the late answer and thank you for taking care of this topic.
The reason why inkscape is installed was to fix the issue #243.
In short, inkscape is a dependency of [nbconvert](https://github.com/jupyter/nbconvert/) to treat SVG in pdf output.
If this seems to be pretty much clear, I don't know exactly when it is required.

The  test `test_nbconvert.py` in `minimal-notebook` passes without the inkscape dependency installed. However we should extend the test to add a new example file with a plot in order to check if the dependency is needed / work in this condition.
If it's the case, we will probably go further on this PR.
Does that sound reasonable to you?

**Comment by mathbunnyru** [comment]
Yes, thanks, @romainx.

**Review by romainx — APPROVED** [review]
Hello,

Just pushed the PR #1182 to test nbconvert with inkscape.
Tests are OK without the explicit dependency but as expected python2 is still installed due to inkscape dependency.

```bash
$ aptitude why python2
# i   inkscape Depends  python2:any
# i A python2  Provides python2:any
```

So as you said **I'm Ok to remove this explicit dependency** even if it does not bring so much improvements as analyzed in this comment https://github.com/jupyter/docker-stacks/issues/1083#issuecomment-629759171

I've asked @parente to review this also in case we missed something.

Thanks for your effort to improve the stacks 👍

**Comment by mathbunnyru** [comment]
Merged the latest master to make sure it still passes all the tests.

**Review by parente — APPROVED** [review]

**Comment by romainx** [comment]
@mathbunnyru, @parente thanks for your help. Let's go for the merge.

**Pull request merged**
