### PR TITLE
Add inkscape to fix SVGs in PDFs

### LINKED ISSUE #243: nbconvert failed: Inkscape svg to pdf conversion failed
I tried converting a trivial notebook (1 markdown cell, 1 code cell, ggplot output) on the latest jupyter/datascience-notebook image (tag: `97a5071c5775`) to a PDF and it failed with a different error than the one in this issue: `nbconvert failed: Inkscape svg to pdf conversion failed`.

Reported in #99 but appears to be a new issue, not the same as the original report.

### PR DESCRIPTION
**Pull request by parente**
Fixes #243

### CODE REVIEW

**Comment by parente** [comment]
@jtyberg want to test out the build process on this one?

**Comment by jakirkham** [comment]
Just as an FYI we have a break at conda-forge due to a new build of OpenBLAS. Fortunately we figured it out pretty quickly and have been making good progress on the issue. However, it is not totally fixed. So, I'd recommend holding off on deploying any Docker images at this time.

**Comment by jtyberg** [comment]
@jakirkham If there's another issue, can you link it here so we know when to pull the trigger?

**Comment by jakirkham** [comment]
Of course. I've been tracking the status of the fixes in this [comment]( https://github.com/conda-forge/openblas-feedstock/pull/9#issuecomment-235320813 ). NumPy is already fixed. SciPy is nearly fixed (waiting on a couple of builds). Still need to fix scikit-learn. I don't think the rest of them are relevant for docker-stacks. Will of course update here when this is done too.

**Comment by jakirkham** [comment]
So we have rebuilt NumPy, SciPy, and scikit-learn. We run their full test suite when doing so. Basically everything but one package on our end has been rebuilt (though the fix is ready). Hoping that is a good indicator that they are now working (famous last words). Feel free to give them a try and let me know if you have any issues.

**Comment by parente** [comment]
@jtyberg if you kick off the build/push, when it's done, please include the tag under which it was pushed to Docker Hub in a comment here once it's available. (A little nicety so the original PR submitter knows it's ready.)

**Comment by jtyberg** [comment]
New stacks are built and pushed to Docker Hub.  Tag is `07a7c4d6d447`.

**Pull request merged**
