### PR TITLE
Upgrade to r-base 3.3.2

### PR DESCRIPTION
**Pull request by parente**
Remove pinning for plotting fix and upgrade other R packages

### CODE REVIEW

**Comment by parente** [comment]
@mingwandroid, looks like rpy2 recipe in the r channel needs an update for compatibility with the new r-base.

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - r-base 3.3.2*
  - rpy2 2.8*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by mingwandroid** [comment]
Oops. I'll do that tomorrow.

**Comment by parente** [comment]
Build looks good now. I tested the 3.3.2 update before sending the PR, so let's give it a go.

**Comment by parente** [comment]
In tag `fa77fe99579b`.

**Pull request merged**
