### PR TITLE
update sympy to 1.0

### PR DESCRIPTION
**Pull request by leosartaj**

### CODE REVIEW

**Comment by parente** [comment]
This keeps failing due to network problems on travis. I'll give it a quick shot here and merge if sympy goes in without issue.

**Comment by leosartaj** [comment]
Okay. Other packages here do not depend on Sympy ASFAIK, so this shouldn't break anything.

**Comment by parente** [comment]
Thanks for the submission!

**Comment by parente** [comment]
Build is underway but might take a bit because docker was upgraded on the build machine and apparently that broke docker cache from the last images.

**Comment by leosartaj** [comment]
Thanks! @parente

**Comment by parente** [comment]
Pushed as 9f5bbec91d6a

**Pull request merged**
