### PR TITLE
Start jupyter-labhub instead of jupyter labhub

### PR DESCRIPTION
**Pull request by cam72cam**
jupyter labhub lacks the hub menu in the top bar

### CODE REVIEW

**Comment by parente** [comment]
@cam72cam Are you still interested in getting this PR merged? It'd be good to know why one form of labhub invocation works while the other doesn't if it's not too hard to check logs and see if there's anything fishy. If nothing jumps out, I can still go ahead and merge this change to at least fix your setup.

**Comment by cam72cam** [comment]
I am, I need to do the test you described and post the results.  Sorry for the delay, other stuff has been taking priority.  I'll try to get to it in the next few days

**Comment by parente** [comment]
Not a problem at all. Wanted to make sure I wasn't dropping the ball here.

**Comment by cam72cam** [comment]
It looks like either I missed something, or the discrepancy has been resolved within the past few months

**Comment by parente** [comment]
Thanks for checking @cam72cam.

**Pull request closed without merging**
