### PR TITLE
Bump Julia to 1.2.0

### PR DESCRIPTION
**Pull request by arnavs**

### CODE REVIEW

**Comment by arnavs** [comment]
@parente Another one of these... `:-P`.

**Comment by jlperla** [comment]
@parente @rkdarst If either of you have a chance to merge and tag, it would be appreciated.  There are jupyterhub solutions effected downstream by this that are hoping to finalize everything before teaching begins next week.

Thanks again for the great resource.

**Comment by arnavs** [comment]
I updated this PR to remove a few packages from Julia: 

* `InstantiateFromURL` --- I develop this package. Added it a while back, but I think pinning the version inside a Jupyter image could confuse people.  

* `RDatasets` and `Gadfly` --- These are useful packages, but probably better to start with just `IJulia` and let people add the precise packages/versions they need. Especially since Julia's resolver will change what operations do, so as to ensure a feasible point for all existing packages. That is, the pre-existing versions may have side-effects for other package operations.

**Comment by parente** [comment]
Sounds reasonable to me. :shipit:

**Comment by jlperla** [comment]
@arnavs  I don't know where the source for it was, but I think that https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-datascience-notebook description should be removed to strip out the packages listed there since this has been merged.

**Pull request merged**
