### PR TITLE
Add FAQ

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Issue ticket if applicable

Fix: https://github.com/jupyter/docker-stacks/issues/1596

## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@trallard would you like to take a look?
https://jupyter-docker-stacks--1883.org.readthedocs.build/en/1883/using/faq.html

**Comment by trallard** [comment]
Hey there. I can have a look this week.

**Comment by mathbunnyru** [comment]
Merging this one 🙂

**Comment by maresb** [comment]
I feel like the FAQ is missing the pun: https://github.com/jupyter/docker-stacks/issues/358#issuecomment-288844834

**Comment by mathbunnyru** [comment]
@maresb nice one!
Done, please, take a look :)

**Comment by maresb** [comment]
Excellent! :smile:

**Pull request merged**
