### PR TITLE
Bump python libs to match other images

### PR DESCRIPTION
**Pull request by parente**
Includes changes from #121 in other stacks so that everything builds successfully off of the minimal-notebook image.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Looking good.

**Comment by parente** [comment]
Tagged `latest` and `9f9907cf1df8` on Docker Hub.

**Comment by willingc** [comment]
@parente At some point, we may wish to enter the short description for the Docker Hub files. It would likely be helpful for the end users especially those that may be using the beta Kitematic on OS X (https://kitematic.com/).

Also, it may make sense at some point to have the images become "official" on Docker Hub. https://docs.docker.com/docker-hub/official_repos/

**Comment by parente** [comment]
@willingc Is there a spot where the descriptions are missing? I thought each one had a short description plus a long description containing a link to the README of each stack here on GitHub.

At one point in the past, I had the README content of each stack duplicated in the long description on Docker Hub. But keeping them in sync with the proper latest version from GitHub turned into a chore. (See issue #12.) I opted for having the link from the long description to the README with the latest, correct documentation over two copies with one out of sync.

**Comment by willingc** [comment]
@parente Ah... I think the ones that you have revised do have the short description in Docker Hub. I noticed a few missing the description such as JupyterHub and configurable-http-proxy. 

On Kitematic (which is supposed to get info from Docker Hub), it looks like the Notebook description isn't updated (weird - caching perhaps).
screen shot 2016-02-14 at 7 08 31 pm

screen shot 2016-02-14 at 7 03 38 pm

**Comment by jakirkham** [comment]
Looks like there is a bug in kitematic ( https://github.com/docker/kitematic/issues/1532 ).

**Pull request merged**
