### PR TITLE
Updated the Example 3 bash script

### PR DESCRIPTION
**Pull request by rehanguha**
Existing script was not able to write contents on the mounted volume.
https://github.com/jupyter/docker-stacks/issues/1472

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@rehanguha thanks for the PR.

I have a few comments about this PR:

1. Do you know the reason, why the default command doesn't work for you? (it works for me fine) It has definitely to do something with host and docker permissions, they might be wrong somewhere.
2. We can't just fix this example, because there are many other examples as well and it won't be consistent. Also, we need to update the docs.

**Comment by rehanguha** [comment]
Note: I am used to docker but I am new to this Jupyter Docker stack.
When I was setting up a new system, I have installed the docker as per the docker website then tried to run the image and I getting an error when ever I was trying to write something inside the work folder.

I tired it multiple times and I was facing the same error.

So, I want to clarify the setting for docker was:
1. https://docs.docker.com/engine/install/ubuntu/
2. https://docs.docker.com/engine/install/linux-postinstall/

I was expecting a simple pull and run like Tensorflow(tensorflow/tensorflow:latest-gpu-jupyter) dockers which I have used before. I just wanted to try Jupyter docker stacks. 😄 

Thank you for commenting.

**Comment by mathbunnyru** [comment]
Ok, then I think we will have to wait for some explanation why this was happening for you.
I'm glad to hear that your issue is resolved and I hope there are not so many people with similar problems.

**Comment by consideRatio** [comment]
So this is a PR to suggest starting the container as root, because the user otherwise may not have access to write to the mounted home directory?

That sounds like a troublesome workaround. If you would then write a file, you would end up making the ownership of that file, within the /home/my-user directory, be root. Which in turn, makes you unable to work with that file later, unless you are root.

I'm sorry to be boring, but I suggest this PR isn't accepted as it seems like a forceful workaround that will cause problems in the end.

**Comment by rehanguha** [comment]
> So this is a PR to suggest starting the container as root, because the user otherwise may not have access to write to the mounted home directory?

Yes. That is the case which is happening. 

> That sounds like a troublesome workaround.

I agree. But I cannot find a better way to write a file to the mounted directory. Please do suggest me a way so that this problem can be solved.

We can closed the PR as it even feel this not a great workaround. But a solutions needs to be in place so that this can be solved.

**Comment by consideRatio** [comment]
> But a solutions needs to be in place so that this can be solved.

My guess is that you can check the user id of the current linux system's user, then set NB_UID to that, mount the current linux system's user's home folder. Then, you will have the correct permissions I think.

What may be in scope of this project is to improve documentation about this.

**Pull request closed without merging**
