### PR TITLE
Use modern GitHub issue templates

### PR DESCRIPTION
**Pull request by mathbunnyru**
Users will separate bugs from feature requests, it should make future maintenance easier.
It's also quite easy to add new issue types (just copy-paste with small changes).

I also deleted some text, because users seem to delete it anyway and I hope they will start using these templates.

Bug report test: mathbunnyru#3
Feature request test: mathbunnyru#5

Recreated this PR from a branch rather than master

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@consideRatio @romainx could you take a look here, please?

**Comment by mathbunnyru** [comment]
@consideRatio may I bother you once again and ask to take a look here?

**Review by consideRatio — APPROVED** [review]
LGTM! Easy to iterate on going onwards so I suggest we go for a merge monday afternoon or similar if no additional comments show up.

**Comment by mathbunnyru** [comment]
It's Monday time :) Merging.

**Pull request merged**
