### PR TITLE
Update DockerHub short descriptions

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
Mesos was removed (one of first PRs I've reviewed here, I suppose, because I don't remember doing it at all 😆).
Otherwise, just some word tweaks.

**Comment by mathbunnyru** [comment]
@consideRatio please take a look.
I think I'm done for today 😂

**Review by consideRatio — APPROVED** [review]

**Comment by consideRatio** [comment]
Nice work @mathbunnyru!!!

**Comment by consideRatio** [comment]
https://github.com/jupyter/docker-stacks/actions/runs/3368890331/jobs/5587937275

> level=error msg="Short description is too long (max 100 characters)"

Triggered by tensorflow-notebook

**Comment by mathbunnyru** [comment]
Don't worry, I've already fixed this (and pushed to `main`) and it got updated on http://hub.docker.com/r/jupyter/tensorflow-notebook

**Pull request merged**
