### PR TITLE
[FAST_BUILD] Add support for Docker/Podman in rootless mode

### PR DESCRIPTION
**Pull request by benz0li**
## Describe your changes

Add support for Docker/Podman in rootless mode.

Enables the container to run as `root` user, e.g.

```bash
podman run -p 8888:8888 -u root -e NB_USER=root -e NB_UID=0 -e NB_GID=0 quay.io/jupyter/scipy-notebook start-notebook.sh --allow-root
```

FYI @anil-resero

## Issue ticket if applicable

Fixes https://github.com/jupyter/docker-stacks/issues/2036

## Checklist (especially for first-time contributors)

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [x] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by benz0li** [comment]
`NB_UID=0` and `NB_GID=0` are mandatory so that the UID/GID is correctly mapped to the host's user.

Due to the additional `cp` option `--no-preserve=ownership`, a `CHOWN_HOME` is not required.

**Comment by mathbunnyru** [comment]
Added `[FAST_BUILD]` to the PR name, to make the build significantly faster.
More info about it: https://github.com/jupyter/docker-stacks/blob/main/.github/workflows/docker.yml#L3-L6

**Comment by manics** [comment]
> IMHO we do not want to use (and touch) the original /root directory.

What's your thinking behind not touching `/root`, but modifying the `root` user? What happens if you create multiple users with the same UID?

```
root@8db194d8497c:/# useradd -m test -u0 --non-unique
root@8db194d8497c:/# su - test
# pwd
/home/test
# id
uid=0(root) gid=1000(test) groups=1000(test)
```

**Comment by benz0li** [comment]
The triplet `-e NB_USER=root -e NB_UID=0 -e NB_GID=0` is strictly required for this use case.

Otherwise you run into

https://github.com/jupyter/docker-stacks/blob/baa110d3f9855f18d8e5db317f48a9591c06cc6b/images/docker-stacks-foundation/start.sh#L70

followed by

https://github.com/jupyter/docker-stacks/blob/baa110d3f9855f18d8e5db317f48a9591c06cc6b/images/docker-stacks-foundation/start.sh#L77 which is supposed to fail.

👉 You cannot remove the user the container is running with (`-u root`).

**Comment by mathbunnyru** [comment]
@manics may I ask you to review this, please?

**Comment by manics** [comment]
It looks like this solves one instance of the problem of running a rootless container without dealing with different subuids.

I'm still not convinced changing root's home directory to `/home/root` is the right approach though. It's true that `/root` may be pre-populated, but so is but since this is the container it's unlikely that there's anything important in there. There's already a well known distinction between root's homedir and standard homedirs, so given that there's going to be confusion regardless of which option is chosen I think sticking with the Linux default is clearer.

Having said that there's actually two different issues being discussed here:
- How should `NB_USER=root NB_UID=0` behave?
- How should `NB_USER=jovyan NB_UID=0` (or any other `NB_USER`) behave? For example, one way to solve the rootless problem is to allow `jovyan` to have `NB_UID=0` which requires `useradd --non-unique`. This isn't perfect since a terminal still shows the username as `root` but `USER=jovyan` and `HOME=/home/jovyan` are correct.

I think it'd be nice to solve the more general problem for rootless running and allow `NB_UID=0` for any `NB_USER`. The specific decision on whether root's home directory should be changed for `NB_USER=root` is something I'm happy for @mathbunnyru to decide since it's a matter of opinion.

**Comment by mathbunnyru** [comment]
Merging this one. I will document the current behaviour in a separate PR.

**Pull request merged**
