### PR TITLE
Updating to reflect changes in how Spark Kernel is build and packaged

### PR DESCRIPTION
**Pull request by lbustelo**
The latest Spark Kernel uses make to build/package. This changes reflect how to build and setup Spark Kernel.

### CODE REVIEW

**Comment by lbustelo** [comment]
Making it a WIP until I get to test the resulting image. Was able to get by an initial issue when building the kernel in the image. Now waiting for the image to finish building the rest of it to test.

**Comment by parente** [comment]
If this works out here, the same change will need to be applied over in jupyter/demo for the try.jupyter.org / tmpnb.org site. It starts from minimal-notebook and installs Spark Kernel along the way.

**Comment by lbustelo** [comment]
It works...
screen shot 2015-12-09 at 2 46 37 pm

**Comment by lbustelo** [comment]
Should I submit another PR for jupyter/demo?

**Comment by parente** [comment]
> Should I submit another PR for jupyter/demo?

Yea. Should be very similar.  I think it was copy/paste coded. Bet it's missing the git sha over there but that should be added too.

I'll merge this and get the build started.

**Comment by parente** [comment]
Build pushed to Docker Hub. Tag 3afdf219f078.

**Pull request merged**
