### PR TITLE
Add nteract front end

### PR DESCRIPTION
**Pull request by willpuckett**
Add an option to use the [nteract front end extension](https://blog.nteract.io/nteract-on-jupyter-53cc2c38290d) in docker-stacks containers. Additional conda forge package is 28MB. 

The nteract front end provides a graphically clean front end interface ideal for both focused development and tidy presentations.

### CODE REVIEW

**Comment by willpuckett** [comment]
I initially PR'ed this to the https://github.com/sakuraiyuta/docker-stacks fork as I intend to use this primarily on ARM, but given [this discussion](https://github.com/jupyter/docker-stacks/issues/1019), as well as its hopeful utility to others, I thought it might make more sense upstream.

**Comment by mathbunnyru** [comment]
Hi @willpuckett!

We've started to encourage fewer additions to the images here and more contributions to the recipes in the documentation (http://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html).

I think a recipe about how to add and configure nteract would make sense in the docs, if someone would like to send a PR (http://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/recipes.html).

Also, as far as I understand, was last released on Jul 16, 2019, so the package is not updated anymore.
And it seems, that there is a deprecation plan.
https://github.com/nteract/nteract/issues/5088#issuecomment-627084372
So, I would rather see this as a recipe than adding to the base image.

**Review by mathbunnyru — CHANGES_REQUESTED** [review]
Commented above the reason for changes

**Comment by willpuckett** [comment]
Thanks Ayaz. I think that's more appropriate as well.

Cheers,
WP

**Comment by mathbunnyru** [comment]
Converting to a draft till it's redone using the recipe approach.

**Comment by willpuckett** [comment]
Closing this. The process for a child image is already well documented, and documenting a deprecated  package seems unnecessary.

**Pull request closed without merging**
