### PR TITLE
Implement run-hooks as a separate script

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Issue ticket if applicable

Work on: https://github.com/jupyter/docker-stacks/issues/1478

## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@benz0li take a look, please.

**Comment by mathbunnyru** [comment]
@benz0li thanks 👍

I think it would be nice if your images somehow were able to update scripts like this, so we have fewer differences and these differences are easier to find. I don't know if it's easy for you or not though.

**Comment by benz0li** [comment]
Very few modifications:

```diff
diff --git a/base/scripts/usr/local/bin/start.sh.orig b/base/scripts/usr/local/bin/start.sh
index d8b97bd..eb62fc7 100755
--- a/base/scripts/usr/local/bin/start.sh.orig
+++ b/base/scripts/usr/local/bin/start.sh
@@ -53,6 +53,8 @@ if [ "$(id -u)" == 0 ] ; then
     # - CHOWN_HOME: a boolean ("1" or "yes") to chown the user's home folder
     # - CHOWN_EXTRA: a comma separated list of paths to chown
     # - CHOWN_HOME_OPTS / CHOWN_EXTRA_OPTS: arguments to the chown commands
+    # - CHMOD_HOME: a boolean ("1" or "yes") to chmod the user's home folder
+    # - CHMOD_HOME_MODE: mode argument to the chmod command
 
     # Refit the jovyan user to the desired the user (NB_USER)
     if id jovyan &> /dev/null ; then
@@ -75,7 +77,7 @@ if [ "$(id -u)" == 0 ] ; then
         fi
         # Recreate the desired user as we want it
         userdel "${NB_USER}"
-        useradd --no-log-init --home "/home/${NB_USER}" --uid "${NB_UID}" --gid "${NB_GID}" --groups 100 "${NB_USER}"
+        useradd --no-log-init --home "/home/${NB_USER}" --shell "$(which zsh)" --uid "${NB_UID}" --gid "${NB_GID}" --groups 100 "${NB_USER}"
     fi
 
     # Move or symlink the jovyan home directory to the desired users home
@@ -97,12 +99,22 @@ if [ "$(id -u)" == 0 ] ; then
                     exit 1
                 fi
             fi
+        # The home directory could be bind mounted. Populate it if it is empty
+        elif [[ "$(ls -A "/home/${NB_USER}" 2> /dev/null)" == "" ]]; then
+            _log "Populating home dir /home/${NB_USER}..."
+            if cp -a /home/jovyan/. "/home/${NB_USER}/"; then
+                _log "Success!"
+            else
+                _log "Failed to copy data from /home/jovyan to /home/${NB_USER}!"
+                exit 1
+            fi
         fi
         # Ensure the current working directory is updated to the new path
         if [[ "${PWD}/" == "/home/jovyan/"* ]]; then
             new_wd="/home/${NB_USER}/${PWD:13}"
             _log "Changing working directory to ${new_wd}"
             cd "${new_wd}"
+            export CODE_WORKDIR=/home/${NB_USER}/projects
         fi
     fi
 
@@ -120,6 +132,10 @@ if [ "$(id -u)" == 0 ] ; then
             chown ${CHOWN_EXTRA_OPTS} "${NB_UID}:${NB_GID}" "${extra_dir}"
         done
     fi
+    # Optionally change the mode of the user's home folder
+    if [[ "${CHMOD_HOME}" == "1" || "${CHMOD_HOME}" == "yes" ]]; then
+        chmod "${CHMOD_HOME_MODE:-755}" "/home/${NB_USER}"
+    fi
 
     # Update potentially outdated environment variables since image build
     export XDG_CACHE_HOME="/home/${NB_USER}/.cache"
@@ -140,6 +156,7 @@ if [ "$(id -u)" == 0 ] ; then
     unset_explicit_env_vars
     _log "Running as ${NB_USER}:" "${cmd[@]}"
     exec sudo --preserve-env --set-home --user "${NB_USER}" \
+        LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}" \
         PATH="${PATH}" \
         PYTHONPATH="${PYTHONPATH:-}" \
         "${cmd[@]}"
@@ -196,7 +213,7 @@ else
             # We cannot use "sed --in-place" since sed tries to create a temp file in
             # /etc/ and we may not have write access. Apply sed on our own temp file:
             sed --expression="s/^jovyan:/nayvoj:/" /etc/passwd > /tmp/passwd
-            echo "${NB_USER}:x:$(id -u):$(id -g):,,,:/home/jovyan:/bin/bash" >> /tmp/passwd
+            echo "${NB_USER}:x:$(id -u):$(id -g):,,,:/home/jovyan:$(which zsh)" >> /tmp/passwd
             cat /tmp/passwd > /etc/passwd
             rm /tmp/passwd
 
```

**Comment by benz0li** [comment]
I think relevant is only the part after `The home directory could be bind mounted. Populate it if it is empty`.  
ℹ️ If the directory is not empty, the script fails.

I have no intention of syncing any files or folders with a pre-populated directory between the host and container.

**Comment by benz0li** [comment]
And the [`populate.sh`](https://github.com/b-data/jupyterlab-python-docker-stack/blob/e0295b86406246873f73d5bc5763866729d9c9d6/base/scripts/usr/local/bin/start-notebook.d/populate.sh) script is required at `/usr/local/bin/start-notebook.d` in case someone *bind mounts* to `/home/jovyan`.

**Comment by benz0li** [comment]
P.S.: I use a similar approach for my [Data Science Dev Containers](https://github.com/b-data/data-science-devcontainers)[^1]: https://github.com/b-data/data-science-devcontainers/blob/main/.devcontainer/scripts/usr/local/bin/onCreateCommand.sh

[^1]: Which are based on my [Language](https://github.com/b-data/julia-docker-stack) [Docker](https://github.com/b-data/python-docker-stack) [Stacks](https://github.com/b-data/r-docker-stack).

**Comment by mathbunnyru** [comment]
I think this PR is ready to go, so I will merge it.

@benz0li I have a few questions though if you don't mind:
1. `Populate it if it is empty` is a bit different from what I would like to do (copy from backup without rewrites).
   Is it a matter of personal choice or do you see some issues with the approach I would like to implement?
2. Why do you need the duplication of the restore step - both in `start.sh` from `/home/jovyan/` and in `populate.sh` from backup-dir?

And two more comments on things I will. change in this project:
1. Thank you for reminding me about specifying `--shell` for useradd. I recently changed `useradd` to use long options and noticed this `useradd` lacks specifying shell (the one in Dockerfile does it correctly). 
2. I will also create a PR with keeping LD_LIBRARY_PATH - it definitely makes sense, thanks! I think people might install some software on top of our image which requires changing LD_LIBRARY_PATH and then if they use another username, it won't work.

**Comment by benz0li** [comment]
> 1. `Populate it if it is empty` is a bit different from what I would like to do (copy from backup without rewrites).
>    Is it a matter of personal choice or do you see some issues with the approach I would like to implement?

This is more of a personal choice. My point of view: Only the original content [from the image] ensures that the container works as intended.

> 2. Why do you need the duplication of the restore step - both in `start.sh` from `/home/jovyan/` and in `populate.sh` from backup-dir? I mean, why can't you always restore for the backup-dir?

1. **Populating `/home/jovyan/` in `populate.sh` with the `start-notebook.d` hook**
    * Use case: `docker run -it --rm -p 8888:8888 -v "${PWD}/<empty-dir>":/home/jovyan jupyter/base-notebook`  
      This ensures that `/home/jovyan/` has the original content before https://github.com/jupyter/docker-stacks/blob/2aa9e0fe363ed6a9b6f4a4777558862e77c63362/images/docker-stacks-foundation/start.sh#L41-L46 i.e. anything else.
2. **Populating `/home/jovyan/` in `start.sh`**
    * Use case: Treat the (empty) bind mounted home directory as a special case of the non-existent one.  
      https://github.com/jupyter/docker-stacks/blob/2aa9e0fe363ed6a9b6f4a4777558862e77c63362/images/docker-stacks-foundation/start.sh#L85 +
      ```bash
      elif [[ "$(ls -A "/home/${NB_USER}" 2> /dev/null)" == "" ]]; then
      ```

ℹ️ This way `start.sh` treats a *bind mount* similar to how Docker treats a *volume*:

> If you start a container which creates a new volume, and the container has files or directories in the directory to be mounted such as `/app/`, Docker copies the directory's contents into the volume. The container then mounts and uses the volume, and other containers which use the volume also have access to the pre-populated content.

– [Volumes | Docker Docs > [...] > Populate a volume using a container](https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container)

👉 This happens only at first run and only if the volume is empty.

**Comment by benz0li** [comment]
@mathbunnyru `elif [[ "$(ls -A "/home/${NB_USER}" 2> /dev/null)" == "" ]]; then` also ensures that the home directory remains untouched on subsequent runs.

**Comment by benz0li** [comment]
Very simple, entirely sane and the outcome easily predictable.

I might extend to

```bash
# The home directory could be bind mounted. Populate it if it is empty
elif [[ "$(ls -A "/home/${NB_USER}" 2> /dev/null)" == "" ]]; then
    _log "Populating home dir /home/${NB_USER}..."
    if cp -a /home/jovyan/. "/home/${NB_USER}/"; then
        _log "Success!"
    else
        _log "ERROR: Failed to copy data from /home/jovyan to /home/${NB_USER}!"
        _log "       The home directory must be empty at the first run!"
        exit 1
    fi
fi
```

i.e. improving the error message on failure.

**Comment by benz0li** [comment]
Cross reference: https://github.com/b-data/jupyterlab-python-docker-stack/issues/1

**Pull request merged**
