### PR TITLE
fix: specify mamba

### PR DESCRIPTION
**Pull request by djangoliv**
Force mamba version

fix issue: https://github.com/jupyter/docker-stacks/issues/1810

### CODE REVIEW

**Comment by bjornjorgensen** [comment]
yes, this seams like the same problem that I have in https://github.com/jupyter/docker-stacks/pull/1812

**Comment by mathbunnyru** [comment]
Let's try to fix this in a better way (this was a hot-fix and I don't want to have it in this repo, if it's possible).
I wrote a message in the issue in the upstream project.

https://github.com/mamba-org/mamba/issues/1583

**Comment by mathbunnyru** [comment]
`mamba-1.0.0` and `micromamba-1.0.0` have been released recently 🎉 
https://github.com/mamba-org/mamba/releases/tag/2022.11.01

I've just checked and now this image builds fine with python 3.8 (again).
So, closing this issue, hope we won't have this problem anymore.

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request closed without merging**
