### PR TITLE
Keras stack introduced

### PR DESCRIPTION
**Pull request by hakandilek**
For #389

### CODE REVIEW

**Comment by parente** [comment]
@hakandilek thanks for this. To cut down on the cost of maintaining all the different stack here, do you think Keras could be added to the exist tensorflow-notebook stack instead? We could rename it for clarity if that's a sticking point.

**Comment by hakandilek** [comment]
@parente well, keras is just one extra pip-package on top of tensorflow. For me it does not make a difference. The question is if someone would like to have that stack without the keras package.

**Comment by parente** [comment]
Since it's just one additional install, it's much lower cost in terms of maintenance and ease for users to add it to the tensorflow image I think. Would you mind making that change to the PR?

**Comment by jakirkham** [comment]
Would add that `keras` is available from `conda-forge` as well.

**Comment by parente** [comment]
Thanks @jakirkham. Let's definitely add this to the conda-install in the tensorflow image. We can rename that image jupyter/deep-notebook or some such if tensorflow is too specific.

**Comment by hakandilek** [comment]
Rolling it back due to #456.

**Pull request closed without merging**
