### PR TITLE
Bump Python 3.9 → 3.10

### LINKED ISSUE #1688: [ENH] - Add a jupyter/minimal-notebook:python-3.10.x image
### What docker image(s) is this feature applicable to?

minimal-notebook

### What changes are you proposing?

I would like to see a `jupyter/minimal-notebook:python-3.10.x` image.

### How does this affect the user?

They can use a newer Python version

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by maresb**
## Describe your changes

Bump Python 3.9 → 3.10

## Issue ticket if applicable

Closes #1688 

## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [X] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
I think we have a test, that checks python version.
Probably need to fix it :)

**Comment by mathbunnyru** [comment]
And, because of our current build system, it's technically impossible to fix this test.

**Comment by maresb** [comment]
Ah, ok. I'm finally back from traveling, so hopefully I can manage to wrap my head around #1703. I'd really like to understand all the clever stuff you're doing there! :smile:

**Comment by mathbunnyru** [comment]
Wow, the test seems to pass. It shouldn’t 😂

**Comment by mathbunnyru** [comment]
@maresb I fixed this test in master. Please, merge it and it should fail now :)

**Comment by maresb** [comment]
@mathbunnyru ok, good, now it's failing as expected.

**Comment by mathbunnyru** [comment]
@maresb this is just a joke 😂

trade_offer

**Comment by maresb** [comment]
Ooh, very tempting! :joy: 

Honestly this weekend is unfortunately looking bleak for me accomplishing any fun work. I'm on the road next week, and I have a lot to prepare.

I'll see if I can download it and have a look for when I'm offline...

**Comment by mathbunnyru** [comment]
No pressure here, @maresb :)
Many of us are doing this for fun, and you can take as long as you need to :)

**Comment by maresb** [comment]
Ah, and I should be clear, I have not tested this myself, so there could be some package further down the chain which is incompatible with 3.10. (But since it's been over ½ year, I think most reputable packages should have adapted by now.)

**Comment by mathbunnyru** [comment]
That's a good point. That's why our current CI builds something strange, then tests it, then incorrectly tags it, and done.
At the same time, the `amd64` workflow should catch problems like this, because it builds what expected and tests it well.

**Comment by maresb** [comment]
Oh, that's great to know! I'm glad that `amd64` tests are working properly.

On the other hand, the `arm64` migration on Conda-Forge is not 100%, so there's a significant probability that something on `amd64` is good on Python 3.10 while `arm64` isn't.

**Comment by bjornjorgensen** [comment]
INFO     test_python:test_python.py:16 Checking that python version is lower than 3.10

Is this one of our tests?

**Comment by bjornjorgensen** [comment]
I open https://github.com/jupyter/docker-stacks/pull/1714 where I have changed the test next python version. I did't run on my github, soo I have open it her.

**Comment by mathbunnyru** [comment]
This will work now, but I will have to rebuild many times, waiting each time for the workflow to complete, to actually update all the images.
I will merge when tests pass.

**Comment by mathbunnyru** [comment]
The test we have for python version is checking the exact match of python version, so the tests should pass.

**Pull request merged**
