### PR TITLE
Update README for current Apache Toree

### LINKED ISSUE #167: Cannot open Scala Notebook
Dear All,

I got the docker image running after "_docker pull jupyter/all-spark-notebook_", but when I access the jupyter notebook interface under localhost:8888, I only see options to create Python2/3, R, and Apache_Toree notebooks. However, I need to create a scala Notebook!

What did I likely miss here?

Best!

### PR DESCRIPTION
**Pull request by parente**
Never got updated when Toree started getting pip installed. Addresses some of the questions in #180, #169. Fixes #167.

### CODE REVIEW

**Comment by Lull3rSkat3r** [comment]
LGTM. When we cut our 0.1.0 release we can sync back up on how to configure `SPARK_OPTS`. We will have docs for the 0.1.0 release we can point you to.

**Comment by parente** [comment]
Yes. We'll need a PR here to update the version # in the Dockerfile anyway (https://github.com/jupyter/docker-stacks/blob/master/all-spark-notebook/Dockerfile#L31) so the README should be adjusted accordingly at that time.

**Comment by parente** [comment]
@jakirkham care to do the merge honors?

**Comment by jakirkham** [comment]
I trust that you guys know what you are doing here. :wink:

Will happily merge though.

**Pull request merged**
