### PR TITLE
Modify the way to change user uid/gid

### LINKED ISSUE #923: Changing UID/GID of user causes large dockers images
Hello everyone!

I'm using the jupyter/base-notebook image when spawning with JHub. Thanks for the capability to change user name, uid and gid!
It seems that using `usermod` in the `start.sh` have an impact on the containers space usage.
I think this is related with a known unresolved bug of Docker with sparse file detailed here: https://github.com/moby/moby/issues/5419
Using `useradd` or `usermod` modifies logs sparse files, not well handled by docker.

There is a workaround for the `useradd` command, using the -l option to prevent writing the log files causing the trouble. But I can't see a similar option in the `usermod` command.

You will find a screenshot of multiple tries made with JHub and a DummyAuthenticator allowing me to test various UIDs. In that example I'm using the NB_USER to also set both NB_UID and NB_GID as well.
Jupyter docker-stacks - UID bug

We clearly see a direct correlation.
Could anyone confirm this issue?

Thanks in advance!

### PR DESCRIPTION
**Pull request by adriendelsalle**
Workaround of a Docker bad handling of sparse files
Fixes #923

### CODE REVIEW

**Comment by adriendelsalle** [comment]
I'm still not sure everything is OK: running a conda create command from a JLab terminal gives me a permission error even if everything looks fine.

**Comment by adriendelsalle** [comment]
Hi @parente, is it possible to have a look on this?
Are you still maintainer of this project?
Thanks!

**Comment by parente** [comment]
Thanks for your patience @adriendelsalle.

> I'm still not sure everything is OK: running a conda create command from a JLab terminal gives me a permission error even if everything looks fine.

Are you still seeing the above problem after making your changes? 

I *think* your code change is functionally equivalent to what we have. It's difficult to tell up front if deleting and re-adding the user will have any side-effects.

**Comment by adriendelsalle** [comment]
Hi @parente 
No problem, it's great you take time to review!

I use this workaround since this summer in my own Dockerfile with no issue/side effect detected (dozen of users were handled by my JHub).
Let me know if I can provide any further test or information on that!

**Comment by parente** [comment]
Let's give it a shot.

**Pull request merged**
