### PR TITLE
Remove mamba pin for aarch64

### LINKED ISSUE #1539: Build is stuck for jupyter/scipy-notebook arm64 image
There is a timeout and it happened several times already:
https://github.com/jupyter/docker-stacks/runs/4292319380?check_suite_focus=true

I think the reason might be in QEMU :(

### PR DESCRIPTION
**Pull request by maresb**
Closes #1539

### CODE REVIEW

**Comment by mathbunnyru** [comment]
Let's indeed try this out, thank you!

**Comment by consideRatio** [comment]
Let's hope for the best! Thanks @maresb !!!

**Comment by maresb** [comment]
I'm trying to follow along in the workflow logs, but I'm confused. There are two workflows:
* Build, test, and publish Docker Images
* Build and test amd64 Docker Images

This seems redundant. Is the point that QEMU is slow so that you can save time by testing without, but you want the publishing workflow to be uniform across all platforms?

**Comment by mathbunnyru** [comment]
Yes, slow build times under QEMU is the reason.
Most of the PRs are enough to be tested under x86_64 only, that's why I implemented a separate workflow.
If a feature is similar for arm and x86 or for x86 only, we can skip long tests and merge PRs faster.

**Comment by maresb** [comment]
Green!!! :tada:

**Comment by consideRatio** [comment]
Wieeeee!!!! :heart: :tada: :rocket:

**Pull request merged**
