### PR TITLE
Fix: Move comment to uncomment packages installation after r-e1071

### LINKED ISSUE #1450: Missing IRkernel from r-notebook
Hi! Thanks for using the Jupyter Docker Stacks.

Please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

Example: `jupyter/r-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -it --rm -p 8888:8888 jupyter/r-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit <http://localhost:8888>
2. Create new notebook
3. Choose kernel

**What do you expect to happen?**

Option to choose kernel should include `IRkernel`. 

**What actually happens?**

Only kernel available is `Python 3 (ipykernel)`

Screen Shot 2021-08-31 at 12 39 16 PM

### PR DESCRIPTION
**Pull request by pabepadu**
Hi,

This PR fix #1450.

The packages following the comment after "r-e1071" are not installed be
To keep the comment I moved it to the line just above.

Regards,

### CODE REVIEW

**Comment by mathbunnyru** [comment]
Thank you so much! This is my mistake :(
Let's see how it goes in the CI, I'm afraid it might break for arm image, but I'm not sure.

**Comment by mathbunnyru** [comment]
@pabepadu I disabled building r-notebook for arm because it is not yet ready.
Could you please merge master to this branch?
I think it should work after this.

**Comment by mathbunnyru** [comment]
I will merge your change as is and then make CI work, it's pretty easy.
Thanks!

**Comment by pabepadu** [comment]
Thank you @mathbunnyru

**Pull request merged**
