### PR TITLE
add CHOWN_CONDA_DIR functionality to start.sh

### PR DESCRIPTION
**Pull request by avinson**
also, improve secure_path sed command.. it's preferable to add a file to /etc/sudoers.d so the change can't be overwritten

### CODE REVIEW

**Comment by GrahamDumpleton** [comment]
If you used ``--add-group`` on docker run, or similar with Kubernetes, to set supplemental groups to include ``100`` I don't think you should need ability to do ``chown``. The images are designed to have key directories/files be writable to group, with supplemental groups being used when UID change and GID is no longer ``users``.

**Comment by GrahamDumpleton** [comment]
Also see https://github.com/jupyter/docker-stacks/pull/555 which is PR for fixing the issues with ownership of directories/files under ``$HOME``. This needs to be done to solve issues with some permissions even when using supplemental group as intended.

**Comment by avinson** [comment]
@GrahamDumpleton thanks for your feedback. If I'm not mistaken, this would be insufficient as it would add `root` to the group specified and not the jovyan user: https://docs.docker.com/compose/compose-file/compose-file-v2/#group_add

**Comment by GrahamDumpleton** [comment]
You are using ``--group-add 100`` so you aren't adding ``root`` to the groups, you are adding the group called ``users``. The ``/opt/conda`` and ``/home/jovyan`` directories are intended to be setup to be group ``users`` and writable by group. This means that when you add ``users`` to supplemental groups when running as UID which results in different primary GID than ``users``, that you can still install packages.

**Comment by avinson** [comment]
Seems that without the `chown` I still get an error (with or without `group-add`, joyvan is GID 100 and seems every file in /opt/conda is group writeable). Maybe some lock file is an issue.. I will try to strace it.

```
(python2) jovyan@82170ccf003b:~$ conda uninstall zlib
Fetching package metadata ...........
Solving package specifications:
Package plan for package removal in environment /opt/conda/envs/python2:

The following packages will be REMOVED:

    zlib: 1.2.11-0 conda-forge

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(337): An error occurred while uninstalling package 'conda-forge::zlib-1.2.11-0'.
PermissionError(13, 'Permission denied')
Attempting to roll back.


PermissionError(13, 'Permission denied')
```

**Comment by GrahamDumpleton** [comment]
What is the actual command you are using to run the container? The ``jovyan`` user is usually UID 1000 not 502 so wondering how you still get it showing as ``jovyan``.

**Comment by avinson** [comment]
@GrahamDumpleton: https://github.com/probcomp/developer/blob/master/docker-compose.yml

**Comment by GrahamDumpleton** [comment]
FWIW I get what is shown down below. I have uninstalling zlib fail for other reasons, but I am likely on main Python 3 environment. I can still install other packages fine.

```
$ docker run --user root --rm -it -e GRANT_SUDO=yes -e NB_UID=502 jupyter/minimal-notebook:latest start.sh
Set username to: jovyan
usermod: no changes
Set jovyan UID to: 502
Granting jovyan sudo access and appending /opt/conda/bin to sudo PATH
Executing the command: bash
jovyan@6820fe1f9afc:~$ id
uid=502(jovyan) gid=100(users) groups=100(users)
jovyan@6820fe1f9afc:~$ conda uninstall zlib
Fetching package metadata .............
Solving package specifications: .

RemoveError: Error: this 'remove' command cannot be executed because it
would require removing 'conda' dependencies

jovyan@6820fe1f9afc:~$ conda install wrapt
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    wrapt: 1.10.11-py36_0 conda-forge

Proceed ([y]/n)? y

wrapt-1.10.11- 100% |######################################| Time: 0:00:01  59.21 kB/s
jovyan@6820fe1f9afc:~$
```


The ``--group-add`` stuff I mentioned is irrelevant to ``--user root -e GRANT_SUDO=yes`` use case because it ensures you are in group ``users`` still anyway. Didn't pick up on the ``sudo`` path as I can't use that as prohibited by container platform. What I need to deal with is:

```
$ docker run --user 100000 --rm -it jupyter/minimal-notebook:latest start.sh
Container must be run as root to set $NB_UID
Container must be run as root to set $NB_GID
Executing the command: bash
I have no name!@9fffbcde6d8a:~$ id
uid=100000 gid=0(root) groups=0(root)
I have no name!@9fffbcde6d8a:~$ touch xxx
touch: cannot touch 'xxx': Permission denied
I have no name!@9fffbcde6d8a:~$ exit
```

This is where ``--group-add`` helps.

```
$ docker run --user 100000 --group-add 100 --rm -it jupyter/minimal-notebook:latest start.sh
Container must be run as root to set $NB_UID
Container must be run as root to set $NB_GID
Executing the command: bash
I have no name!@31dcf44e52d3:~$ id
uid=100000 gid=0(root) groups=0(root),100(users)
I have no name!@31dcf44e52d3:~$ touch xxx
I have no name!@31dcf44e52d3:~$ exit
```

Which notebook image is yours based on and what changes do you make on top?

If you are installing extra packages in image layer on top, is important to call ``fix-permissions`` as shown in:

* https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L85

That is even wrong, as meant to also do it on home directory as well. Thus:

```
fix-permissions $CONDA_DIR && \
fix-permissions /home/$NB_USER
```

So make sure you are running ``fix-permissions``. If you don't the directories/files of stuff can be left without group write, which means when relying on that in container, will not be able to install, or potentially install, depending on what directories/files it is.

**Comment by GrahamDumpleton** [comment]
If it is:

* https://hub.docker.com/r/probcomp/notebook/~/dockerfile/

That doesn't fix up permissions as describe and so could be issue.

**Comment by parente** [comment]
@avinson In your Dockerfile, you set a custom `$NB_UID`, but the default group to which `jovyan` belongs, the `users` group, still has write permission on `/opt/conda` and all subdirs, even without chowning it:

```
jovyan@bde8ff262a6a:~$ ls -l /opt/conda/
total 52
drwsrwsr-x 1 jovyan users 4096 Jan 17 01:50 bin
drwsrwsr-x 1 jovyan users 4096 Jan 17 01:50 conda-bld
drwsrwsr-x 1 jovyan users 4096 Jan 17 01:50 conda-meta
drwsrwsr-x 2 jovyan users 4096 Jan 17 01:47 envs
drwsrwsr-x 1 jovyan users 4096 Jan 17 01:50 etc
drwsrwsr-x 1 jovyan users 4096 Jan 17 01:49 include
drwsrwsr-x 1 jovyan users 4096 Jan 17 01:49 lib
-rw-rw-r-- 1 jovyan users 4299 Sep 19 22:55 LICENSE.txt
drwsrwsr-x 1 jovyan users 4096 Jan 17 01:50 pkgs
drwsrwsr-x 1 jovyan users 4096 Jan 17 01:50 share
drwsrwsr-x 4 jovyan users 4096 Jan 17 01:48 ssl
drwsrwsr-x 3 jovyan users 4096 Jan 17 01:47 x86_64-conda_cos6-linux-gnu
```

**Comment by avinson** [comment]
@GrahamDumpleton thanks.. `fix-permissions` resolved the issue. however, my fix for sudoers path is still relevant. will submit as a separate PR.

**Comment by avinson** [comment]
fyi: https://github.com/jupyter/docker-stacks/pull/556

**Pull request closed without merging**
