### PR TITLE
Upgrade Python in scipy-notebook to 3.7

### PR DESCRIPTION
**Pull request by alasdairtran**
This PR pins the Python version to prevent Conda from downgrading (e.g. from 3.7 to 3.6). It also updates two packages, `numba` and `h5py`, to make them compatible with Python 3.7.  Fixes issue #768

### CODE REVIEW

**Comment by parente** [comment]
Build fails consistently after 10 minutes of solving conda dependencies in the tensorflow image with no output. We can try merging and see what happens with the build on Docker Cloud, and revert if it causes trouble there.

**Comment by alasdairtran** [comment]
> Build fails consistently after 10 minutes of solving conda dependencies in the tensorflow image with no output. We can try merging and see what happens with the build on Docker Cloud, and revert if it causes trouble there.

Actually I think Tensorflow hasn't officially supported Python 3.7 yet. We can track the issue [here](https://github.com/tensorflow/tensorflow/issues/20517).

Let's wait for Tensorflow 1.13 to be released before merging my PR.

**Comment by parmentelat** [comment]
my understanding is that tensorflow was released as 1.13 a short while ago  
is there anything that needs to be done explicitly to get this back on track ?

**Comment by parente** [comment]
Resolved the merge conflict using the nice new GH editor for that, and kicked off a build to see where we stand.

**Comment by parente** [comment]
```
SpecsConfigurationConflictError: Requested specs conflict with configured specs.
  requested specs: 
    - keras=2.2
    - tensorflow=1.12
  pinned specs: 
    - python=3.7
Use 'conda config --show-sources' to look for 'pinned_specs' and 'track_features'
configuration parameters.  Pinned specs may also be defined in the file
/opt/conda/conda-meta/pinned.
```

Next step is for the PR to update versions.

**Comment by parmentelat** [comment]
Hey folks; I'd love to see this come through, is there anything I can do to help out on this one ?

**Comment by maracuja-juice** [comment]
The referenced PR was merged 2 days ago :sparkles:

**Comment by parente** [comment]
Rebased on master and rebuilding with tf 1.13

**Comment by parente** [comment]
Build is green. Thanks for the contributions and patience everyone!

**Pull request merged**
