### PR TITLE
Only install system packages which are useful for many people

### PR DESCRIPTION
**Pull request by mathbunnyru**
Fix: https://github.com/jupyter/docker-stacks/issues/1588

### CODE REVIEW

**Comment by consideRatio** [comment]
I appreciate having comments for everything we have included, so that there is clarity for long term maintenance about the purpose/value of all packages.

I cant say if these will be reasonabe to remove or not in practice. I'm okay doing it but would appreciate additional reviewers!

**Comment by mathbunnyru** [comment]
I suppose, if some package is really needed for some crucial feature, we should:
- docs, why this package is needed, and what feature won't work (inline docs like these help a lot)
- test, which tests the feature (not just the package)
- if we delete the package, the users will come with - "hey, this feature doesn't work after the update" and we will add the package back with something from above
- super-useful package, like `wget` or `vim` is also ok

So, in general, I'm not afraid of changes like that :)

**Review by consideRatio — APPROVED** [review]
Thanks for your thorough work!! ♥️🎉

**Comment by mathbunnyru** [comment]
Let's merge this, I don't think this will cause us many problems.

**Pull request merged**
