### PR TITLE
Refactor Makefile to improve readability

### PR DESCRIPTION
**Pull request by mathbunnyru**

### CODE REVIEW

**Comment by consideRatio** [comment]
Restarted tests that failed like this.

```
=================================== FAILURES ===================================
_____________________________ test_python_packages _____________________________

package_helper = <helpers.CondaPackageHelper object at 0x7fe9f782a0d0>
python_packages = <map object at 0x7fe9f782ae50>, max_failures = 0

    def test_python_packages(package_helper, python_packages, max_failures=0):
        """Test the import of specified python packages"""
>       return _import_packages(
            package_helper, python_packages, check_import_python_package, max_failures
        )

test/test_packages.py:158: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

package_helper = <helpers.CondaPackageHelper object at 0x7fe9f782a0d0>
filtered_packages = <map object at 0x7fe9f782ae50>
check_function = <function check_import_python_package at 0x7fe9f783a1f0>
max_failures = 0

    def _import_packages(package_helper, filtered_packages, check_function, max_failures):
        """Test if packages can be imported
    
        Note: using a list of packages instead of a fixture for the list of packages since pytest prevents use of multiple yields
        """
        failures = {}
        LOGGER.info("Testing the import of packages ...")
        for package in filtered_packages:
            LOGGER.info(f"Trying to import {package}")
            try:
                assert (
                    check_function(package_helper, package) == 0
                ), f"Package [{package}] import failed"
            except AssertionError as err:
                failures[package] = err
        if len(failures) > max_failures:
>           raise AssertionError(failures)
E           AssertionError: {'ca-certificates': AssertionError('Package [ca-certificates] import failed\nassert 1 == 0\n  +1\n  -0'), 'openssl': AssertionError('Package [openssl] import failed\nassert 1 == 0\n  +1\n  -0')}

test/test_packages.py:142: AssertionError
------------------------------ Captured log setup ------------------------------
INFO     helpers:helpers.py:50 Starting container jupyter/tensorflow-notebook ...
INFO     conftest:conftest.py:80 Running jupyter/tensorflow-notebook with args {'detach': True, 'ports': {'8888/tcp': 8888}, 'tty': True, 'command': ['start.sh', 'bash', '-c', 'sleep infinity']} ...
INFO     helpers:helpers.py:76 Grabing the list of specifications ...
------------------------------ Captured log call -------------------------------
INFO     test_packages:test_packages.py:132 Testing the import of packages ...
INFO     test_packages:test_packages.py:134 Trying to import mamba
INFO     test_packages:test_packages.py:134 Trying to import conda
INFO     test_packages:test_packages.py:134 Trying to import pip
INFO     test_packages:test_packages.py:134 Trying to import jupyterlab
INFO     test_packages:test_packages.py:134 Trying to import notebook
INFO     test_packages:test_packages.py:134 Trying to import jupyterhub
INFO     test_packages:test_packages.py:134 Trying to import sklearn
INFO     test_packages:test_packages.py:134 Trying to import bs4
INFO     test_packages:test_packages.py:134 Trying to import ipympl
INFO     test_packages:test_packages.py:134 Trying to import sqlalchemy
INFO     test_packages:test_packages.py:134 Trying to import xlrd
INFO     test_packages:test_packages.py:134 Trying to import tables
INFO     test_packages:test_packages.py:134 Trying to import sympy
INFO     test_packages:test_packages.py:134 Trying to import cloudpickle
INFO     test_packages:test_packages.py:134 Trying to import seaborn
INFO     test_packages:test_packages.py:134 Trying to import numexpr
INFO     test_packages:test_packages.py:134 Trying to import patsy
INFO     test_packages:test_packages.py:134 Trying to import ipywidgets
INFO     test_packages:test_packages.py:134 Trying to import scipy
INFO     test_packages:test_packages.py:134 Trying to import matplotlib
INFO     test_packages:test_packages.py:134 Trying to import h5py
INFO     test_packages:test_packages.py:134 Trying to import dill
INFO     test_packages:test_packages.py:134 Trying to import bokeh
INFO     test_packages:test_packages.py:134 Trying to import skimage
INFO     test_packages:test_packages.py:134 Trying to import pandas
INFO     test_packages:test_packages.py:134 Trying to import altair
INFO     test_packages:test_packages.py:134 Trying to import widgetsnbextension
INFO     test_packages:test_packages.py:134 Trying to import dask
INFO     test_packages:test_packages.py:134 Trying to import bottleneck
INFO     test_packages:test_packages.py:134 Trying to import statsmodels
INFO     test_packages:test_packages.py:134 Trying to import cython
INFO     test_packages:test_packages.py:134 Trying to import numba
INFO     test_packages:test_packages.py:134 Trying to import tensorflow
INFO     test_packages:test_packages.py:134 Trying to import ca-certificates
INFO     test_packages:test_packages.py:134 Trying to import certifi
INFO     test_packages:test_packages.py:134 Trying to import openssl
=========================== short test summary info ============================
FAILED test/test_packages.py::test_python_packages - AssertionError: {'ca-cer...
================== 1 failed, 3 passed, 1 deselected in 23.63s ==================
make: *** [Makefile:129: test/tensorflow-notebook] Error 1
make: Leaving directory '/home/runner/work/docker-stacks/docker-stacks/main'
```

**Comment by mathbunnyru** [comment]
Thanks! I think it should work. At least I hope it will :)

**Comment by consideRatio** [comment]
Did the docker image fail to install the package correctly without crashing, and then the test correctly captured the failed image?

**Comment by mathbunnyru** [comment]
I will take a look in a few minutes.

**Comment by mathbunnyru** [comment]
I made a quick-fix, where openssl and ca-certificates are not imported.

**Comment by consideRatio** [comment]
Do you know what made this fail now but not before? Do you think we suddenly ended up installing openssl and ca-certificates via conda but didn't before - because of upstream changes to dependencies or similarly?

**Comment by mathbunnyru** [comment]
> Do you know what made this fail now but not before? Do you think we suddenly ended up installing openssl and ca-certificates via conda but didn't before - because of upstream changes to dependencies or similarly?

They were installed before, but it seems that now they are considered to be manually installed, that's why they are imported.
I don't actually want to investigate this problem too much, as soon it doesn't bother us too much.

**Review by consideRatio — APPROVED** [review]

**Pull request merged**
