### PR TITLE
Update debian base image for CVEs

### PR DESCRIPTION
**Pull request by parente**
https://github.com/docker-library/official-images/pull/1695

### CODE REVIEW

**Comment by parente** [comment]
Have been unable to build and push this so far. Every attempt is met with failure apt-get installing a random package from the large list of packages in minimal-notebook. Rate limit?

**Comment by rgbkrk** [comment]
Does the host need to be updated, DNS cache cleaned out?

**Comment by parente** [comment]
Nope. 10th try in a row was a charm.

**Comment by rgbkrk** [comment]
Ah yes the good old "do it 10 times and then it works" trick.

**Pull request merged**
