### PR TITLE
Run github pipelines in ubuntu 22.04

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Describe your changes

Let's update and pin Ubuntu versions for GitHub runners as well.

https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/

## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by bjornjorgensen** [comment]
-1 for this.

"Otherwise, our recommendation is to use ubuntu-latest, which currently utilizes Ubuntu 20.04 but will begin running on Ubuntu 22.04 in the near future. This will ensure your workflows are always using a recent OS and removes the need to constantly update workflow files with image versions."

Lets use `ubuntu-latest`

**Comment by mathbunnyru** [comment]
Well, my motivation is that arm runners have ubuntu 22.04, that's why to make everything in sync, it makes sense to me to use the same Ubuntu version on GitHub runners as well.

**Comment by bjornjorgensen** [comment]
ok, but we have it as github recommends. So I don't find any reasons to change that. 

We will get 22.04 when github recommends that.

**Comment by mathbunnyru** [comment]
I'm ok keeping it `ubuntu-latest`.

**Comment by bjornjorgensen** [comment]
[GitHub Actions: Larger Runners using Ubuntu-latest label will now use Ubuntu-22.04](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/)

**Comment by mathbunnyru** [comment]
> @mathbunnyru
> [GitHub Actions: Larger Runners using Ubuntu-latest label will now use Ubuntu-22.04](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/)

Got it, thanks.

**Pull request closed without merging**
