### PR TITLE
bump Julia version (1.1.0 => 1.1.1)

### PR DESCRIPTION
**Pull request by arnavs**
Use the latest stable version of Julia.

### CODE REVIEW

**Comment by parente** [comment]
Thanks for the PR @arnavs. If you're feeling up to it, the SHA256 a few lines below the Julia download+install steps in the Dockerfile also has to be updated to match that of the Julia 1.1.1 release so that the build succeeds.

**Comment by arnavs** [comment]
Thanks @parente; done.

**Comment by arnavs** [comment]
@parente Wanted to bump you on this.

**Comment by parente** [comment]
Thanks @arnavs!

**Pull request merged**
