### PR TITLE
Add write permissions to github jobs

### PR DESCRIPTION
**Pull request by mathbunnyru**
**NOTE: someone more experienced in GitHub actions should tell that this is fine.**

Also, there is no way I could check this (because my permissions are very limited)

Fix: https://github.com/jupyter/docker-stacks/issues/1280

The advice I used: https://github.com/jupyterhub/team-compass/issues/404#issue-863678103

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@consideRatio could you tell me, what do you think? Is this OK or not?

**Comment by mathbunnyru** [comment]
I suggest we don't make quick assumptions and take time because skipping manifests for a few builds is not really a big issue.
Security issues are much more important in this case.

So please, take your time.

**Comment by romainx** [comment]
@mathbunnyru seems to be the right thing to do. Permissions cannot be set at lower level so I do not see a better way of fixing the issue.

**Comment by mathbunnyru** [comment]
I also searched for setting permissions on a lower level and it is indeed seems to be impossible.
Also I thought about having a separate job for pushing, but that is not something easily done, because we need the artefacts from the upper build commands in the job.

**Review by consideRatio — APPROVED** [review]
Adding write permissions for `conents` seems correct. I don't think there is a more appropriate scoped permission than this based on [these docs](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token).

I suggest merge and see what happens :)

**Comment by romainx** [comment]
Strike while the iron is hot 🔨

**Comment by mathbunnyru** [comment]
Haha, ok, let's try it out :)

**Comment by mathbunnyru** [comment]
At least it worked for the strings pushing.
https://github.com/jupyter/docker-stacks/commit/ccc1470b027dc72ce207b9f3d9cb3db06224398f
So there are some chances it will work for the wiki as well.

**Comment by mathbunnyru** [comment]
It works now 👍 
https://github.com/jupyter/docker-stacks/runs/2495304110

**Comment by romainx** [comment]
It worked 🎉 Great
Just a line feed to fix 😄 
Home_·_jupyter_docker-stacks_Wiki

**Comment by mathbunnyru** [comment]
Yes, I also noticed it :)

Give me a sec, I will take a look why it's wrong :)

**Comment by romainx** [comment]
Enough merge for tonight :sweat_smile:
We will fix it later.

**Comment by mathbunnyru** [comment]
> Enough merge for tonight 😅
> We will fix it later.

Sorry, already done.
https://github.com/jupyter/docker-stacks/pull/1284

**Pull request merged**
