### PR TITLE
Bump to Spark 1.6.0 with Apache Toree

### PR DESCRIPTION
**Pull request by parente**
Should be merged **AFTER** PR #112

* Use Spark 1.6.0
* Use Apache Toree (new name/home of ibm-et/spark-kernel)
* Add missing pub key for binary
* Add SHA check for spark package download

### CODE REVIEW

**Comment by jakirkham** [comment]
Is there anything else about this that is WIP other than the PR it is dependent on?

**Comment by rgbkrk** [comment]
#112 is in, looking forward to Toree.

**Comment by parente** [comment]
I'd like to get the other PR built first and pushed to Docker Hub as one version of the image. Then get this in and build it as the next version.

**Comment by parente** [comment]
This can go in now.

**Comment by jakirkham** [comment]
I assume you already tested this.

**Comment by parente** [comment]
tnx @jakirkham. I'll post the tag back here.

**Comment by parente** [comment]
Pushed to Docker Hub and tagged as `55d5ca6be183`.

**Pull request merged**
