### PR TITLE
add sqlalchemy to conda install command

### PR DESCRIPTION
**Pull request by midnightradio**
workaround for the issue #248

### CODE REVIEW

**Comment by jtyberg** [comment]
@midnightradio Can you add sqlalchemy to the python3 conda install as well?  We should explicitly install it in both environments, rather than rely on it being pulled in.

**Comment by midnightradio** [comment]
Not only that, I added some mysql drivers which would not make the package useless at least for MySQL users.

**Comment by parente** [comment]
Hmm. I was fine with adding the sqlalchemy package, but adding the mysql driver / client goes too far I think. If we add mysql, now where do we draw the line when other folks ask for postgres, maria, Oracle, ... The image will be bloated with maybe 1-2 drivers a few people use, and many that most people never touch.

How about we simply add the SQLAlchemy lib to the Python 2 and 3 environments explicitly, and then add to the [recipes wiki page](https://github.com/jupyter/docker-stacks/wiki/Docker-recipes) about how to create new Docker images deriving from the stacks to install specific database engines?

**Comment by midnightradio** [comment]
Maybe I was personally hoping that I could use the image anywhere with no changes and went too far. I agree with your words. In build testing before updating my PR.

**Comment by parente** [comment]
Not a problem and thanks for understanding. It's *really* hard to put a strict definition on what should and shouldn't go in the images here.

**Comment by jtyberg** [comment]
New Docker images are built with tag `1d374670daaa`.

**Pull request merged**
