### PR TITLE
Spark 2.3

### PR DESCRIPTION
**Pull request by Bidek56**
Since Spark 2.3 is out, may as well use it.

### CODE REVIEW

**Comment by Bidek56** [comment]
The Travis CI job failed because of: The job exceeded the maximum time limit for jobs, and has been terminated.
How do you build it in order to finish successful?

**Comment by parente** [comment]
The travis build exists to vet PRs and run the tests. The images built there are not what ultimately land on Docker Hub. They rebuild after merge to master on Docker Cloud itself.

This is the first time I've seen the build timeout. It's unsurprising that it eventually happened, though, considering how many images we build and how big they've gotten. I've restarted just to see if it runs quicker the next time through. If not, I'll have a look at the logs to see if there's a problematic hang or if we should just go ahead and merge.

It might be time to shed some image definitions, split the repo, trim some packages, ...

**Comment by Bidek56** [comment]
It builds fairly quickly on my Azure box, maybe the Travis CI box is slow or had a lot of activity during the  end of the work day EST.

**Comment by Bidek56** [comment]
It's failing on: 

docker build  --rm --force-rm -t jupyter/all-spark-notebook:latest ./all-spark-notebook

If the CI is setup to build all the notebooks for one PR, then it needs more than an hour to build them.
Why are we building all of the images for one PR?

**Comment by parente** [comment]
>Why are we building all of the images for one PR?

This can certainly be optimized. Code could check what files changed in git, what images they impacts, and only rebuild those images and downstream.

**Comment by Bidek56** [comment]
If we are re-building all the images, how do we increase the CI time so it does not time out?

**Comment by parente** [comment]
The build failure is related to the max build time allowed on Travis. I've opened #577 so we can address that problem separately.

I haven't had a lot of time recently to contribute to open source and don't look to have a lot coming up. That said, I don't want this PR to block waiting for the Travis fix. We can move ahead with merging it. If there is a true problem with the Docker image, it will simply fail to build on Docker Cloud and won't be available for people to use anyway.

If this sounds reasonable, let me know and I (or someone) can hit the merge button.

**Comment by Bidek56** [comment]
Please approve the PR so we can use it from Docker Hub. Thanks!!

**Comment by Bidek56** [comment]
It build on Docker Hub -> jupyter/pyspark-notebook:de0cd8011b9e

**Pull request merged**
