### PR TITLE
Bump Spark to 1.6.1, Toree to 0.1.0.dev7

### PR DESCRIPTION
**Pull request by lbustelo**
Based on #202 but moving Toree to dev7

/cc @parente

### CODE REVIEW

**Comment by parente** [comment]
Need to fix the checksum value in the dockerfile for wget fetched spark zip.

**Comment by lbustelo** [comment]
fixing checksum...

**Comment by lbustelo** [comment]
should be good to merge

**Comment by parente** [comment]
Fixes #170. Build + push to docker hub is running now. The wiki build page will update when done.

**Pull request merged**
