### PR TITLE
Make use of available environment variables

### PR DESCRIPTION
**Pull request by eigengrau**
base-notebook defines environment variables for the Conda install path and the
notebook user. However, in some instances, these locations were still hardcoded.
Let’s use the variables instead.

### CODE REVIEW

**Comment by parente** [comment]
I think docker used to treat env vars in `USER` statements as literal usernames and not fail in any noticeable way. Can you confirm that ops in the dockerfile are indeed using `jovyan` and not a `$NB_USER` user?

**Comment by eigengrau** [comment]
> Can you confirm that ops in the dockerfile are indeed using jovyan and not a $NB_USER user?
Ran the containers; can confirm that the variables are evaluated.

```
Step 34 : USER $NB_USER
 ---> Using cache
 ---> e59282e100b1
Step 35 : RUN id
 ---> Running in 50b55c952f16
uid=1000(jovyan) gid=100(users) groups=100(users)
```

**Comment by parente** [comment]
Thanks for the quick check. There's a series of PRs that came in last night and we still do pushes to dockerhub somewhat manually. I'll get this in, in order.

**Comment by parente** [comment]
Merging but grouping it in a single build/push to DockerHub with #224 and #227 to avoid multiple, giant pushes for minor, independent changes (I hope).

**Pull request merged**
