### PR TITLE
Move the overview image up on README page

### PR DESCRIPTION
**Pull request by willingc**
I really like this image and want to move it higher on the page so it catches more views :smile:

### CODE REVIEW

**Comment by jakirkham** [comment]
Sure, I'm ok with that. @parente, thoughts?

Also, @willingc feel free to add `[ci skip]` to these sorts of commits. No need to build docker images for doc changes. :smile:

**Comment by willingc** [comment]
@jakirkham Sure. Where do I put [ci skip] in the commit message or somewhere in the PR? Learning something new. Cool.

**Comment by jakirkham** [comment]
Normally, I stick with the commit message as most CIs know how to handle that. Though some will add a merge commit with `master` that includes the PR title. In that case, the PR title will work too. No need to do it now though.

**Comment by jakirkham** [comment]
I'm going to go ahead and merge this. We can always play with the Readme more. I think @parente is probably busy.

**Comment by parente** [comment]
It's OK. My only comment is that this feels more like how stuff works under the hood and that it might scare off some users who just want to get an image and run it.

**Comment by jakirkham** [comment]
Fair enough, what if we add a brief summary before that just gives a feel as to how the stacks are grouped and then segue to the diagram. Do you think that would make the transition a little nicer?

**Comment by willingc** [comment]
@parente and @jakirkham Alternatively, a new visual might be created. What I liked about this one is that it gave a very easy view of all the different stacks that are available. 

Thanks for the CI tip too.

**Pull request merged**
