### PR TITLE
Documentation updates 

### PR DESCRIPTION
**Pull request by rigzba21**
Adding documentation updates regarding https://github.com/jupyter/docker-stacks/issues/1333

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@rigzba21 could you please fix the style issue?

**Comment by mathbunnyru** [comment]
I fixed the style where it didn't match previous style.

**Review by mathbunnyru — APPROVED** [review]
I think this looks good.

@consideRatio what's your opinion?

**Review by consideRatio — APPROVED** [review]
LGTM, thanks @rigzba21 and @mathbunnyru! :heart: :tada:

**Pull request merged**
