### PR TITLE
Rebase all-spark-notebook on pyspark-notebook

### PR DESCRIPTION
**Pull request by parente**
Closes https://github.com/jupyter/docker-stacks/pull/161

To speed up build, reduce accidental disparity, ease maintenance.

### CODE REVIEW

**Comment by parente** [comment]
If this goes green and we decide to merge, we can probably ignore #161 which is included here by definition.

/cc @jakirkham

**Comment by parente** [comment]
This shaves about 6 minutes off the build. If this looks good to you @jakirkham , I think we can merge this one in and forget about #161.

**Comment by jakirkham** [comment]
Looks great @parente. Should also reduce our maintenance burden, which I am always a fan of. :)

**Comment by jakirkham** [comment]
Do you want to rebuild or should I?

**Comment by parente** [comment]
You can do the honors. Tnx!

**Comment by jakirkham** [comment]
Looks like there was release of the Debian image. Should we upgrade too?

**Comment by jakirkham** [comment]
Nevermind it has the same sha so not really different.

**Comment by jakirkham** [comment]
Running in tmux session 0.

**Comment by jakirkham** [comment]
Released. :)

**Comment by parente** [comment]
:tada:

**Comment by jakirkham** [comment]
Yeah, this is helping reduce CI time for sure. (~35 min) Still long. Will need to investigate with the VM.

**Pull request merged**
