### PR TITLE
Update README links

### PR DESCRIPTION
**Pull request by willingc**
Update files for changed link.

### CODE REVIEW

**Comment by jakirkham** [comment]
Yeah, @parente and I were talking about this before. Maybe you have some thoughts on this, @willingc.

It seems like there is a lot of repetition in the READMEs. One thing that would aid updates like this is if we generate the repeated parts using a common source document. This would allow one to make one change in one place and propagate it. The main downside is that updating the READMEs becomes a little bit more complicated.

**Comment by jakirkham** [comment]
LGTM. Are there more changes planned here? Anything else we need to wait for here?

**Comment by willingc** [comment]
@jakirkham No more changes right now. I'll ask around at the next couple of conferences that I'm at for tips on the best way/simplest way to minimize the repetition. Thanks. On another note, I have been working with Docker on OS X Beta and it is soooooooo much better than boot2docker.

**Comment by jakirkham** [comment]
Sounds good. In it goes. Thanks @willingc.

**Comment by jakirkham** [comment]
Thanks for looking into how to reduce repetition in doc maintenance.

Ooh. I need to try that. Still rocking `docker-machine` ATM. `boot2docker` was painful. Getting rid of the old CLI helped.

**Pull request merged**
