### PR TITLE
Document NOTEBOOK_ARGS

### PR DESCRIPTION
**Pull request by mathbunnyru**
Fix: https://github.com/jupyter/docker-stacks/issues/1541

### CODE REVIEW

**Comment by mathbunnyru** [comment]
The issue is already resolved, but adding docs will help other users in the future.
Waiting for someone to merge or comment :)

**Comment by consideRatio** [comment]
LGTM thanks for your work @mathbunnyru!!

**Comment by mathbunnyru** [comment]
Just doing what I can :)

**Comment by consideRatio** [comment]
which is a lot of great things :)

**Pull request merged**
