### PR TITLE
Docker linting -> Hadolint

### PR DESCRIPTION
**Pull request by romainx**
Hello,

Here is a proposal and a draft of using the [Hadolint][LK1] tool to analyse each `Dockerfile` to comply with [Docker best practices][LK2].

I've fixed most of the linting issues however I may have break something. I will take some times to check.

Best

[LK1]: https://github.com/hadolint/hadolint
[LK2]: https://docs.docker.com/develop/develop-images/dockerfile_best-practices

### CODE REVIEW

**Comment by romainx** [comment]
I think I'm done, ready for the review :bowtie:

**Comment by mathbunnyru** [comment]
@romainx this seems to be a nice tool to check dockerfiles, thanks!
I will definitely run it on my own dockerfiles :)

May I suggest you create a config file with 2 ignore rules:
DL3006 (version in FROM) and DL3008 (version in apt-get)

I think it makes sense to ignore these 2 rules, because they are ignored quite a lot in these dockerfiles.

**Comment by romainx** [comment]
@mathbunnyru very good suggestion, thank you! 
It has been taken into account (and documented in the `lint.md`.

Many thanks for your feedback.

**Comment by parente** [comment]
Add `hadolint` makes sense to me. The PR looks good, including the new doc sections, and I agree with the exceptions @mathbunnyru suggested. Let's :shipit:.

**Pull request merged**
