### PR TITLE
conda 4.7.5

### LINKED ISSUE #878: conda environment inconsistency in scipy-notebook
**What docker image you are using?**
`jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it jupyter/scipy-notebook bash`

**What steps do you take once the container is running to reproduce the issue?**
 `conda update --all`
(or `conda`command that will try to install something)

**What do you expect to happen?**
No warmings reported by conda

**What actually happens?**
`conda` reports an environment inconsistency 

> Collecting package metadata: done
> Solving environment: \ 
> The environment is inconsistent, please check the package plan carefully
> The following packages are causing the inconsistency:
> 
>   - conda-forge/linux-64::matplotlib==3.0.3=py37_1
> done

### LINKED ISSUE #891: conda update breaks CONDA_VERSION
In base-notebook/Dockerfile, a version of conda is choosen :
```
ENV MINICONDA_VERSION=4.5.12 
    CONDA_VERSION=4.6.7
...
$CONDA_DIR/bin/conda install --quiet --yes conda="${CONDA_VERSION%.*}.*"
```

but an update breaking version is done :
`$CONDA_DIR/bin/conda update --all --quiet --yes`

I guess building is not reproductible. In my case, using conda 4.7.5 leads to a tedious error during conda update :

```
...
  prompt_toolkit     conda-forge/noarch::prompt_toolkit-2.0.9-py_0
  ptyprocess         conda-forge/noarch::ptyprocess-0.6.0-py_1001
  pycurl             conda-forge/linux-64::pycurl-7.43.0.2-py37h16ce93b_1
  pygments           conda-forge/noarch::pygments-2.4.2-py_0
  pyjwt              conda-forge/noarch::pyjwt-1.7.1-py_0
  pyrsistent         conda-forge/linux-64::pyrsistent-0.15.2-py37h516909a_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  python-editor      conda-forge/noarch::python-editor-1.0.4-py_0
  pyzmq              conda-forge/linux-64::pyzmq-18.0.1-py37hc4ba49a_1
  send2trash         conda-forge/noarch::send2trash-1.5.0-py_0
  sqlalchemy         conda-forge/linux-64::sqlalchemy-1.3.5-py37h516909a_0
  terminado          conda-forge/linux-64::terminado-0.8.2-py37_0
  testpath           conda-forge/noarch::testpath-0.4.2-py_1001
  tornado            conda-forge/linux-64::tornado-6.0.3-py37h516909a_0
  traitlets          conda-forge/linux-64::traitlets-4.3.2-py37_1000
  wcwidth            conda-forge/noarch::wcwidth-0.1.7-py_1
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  zeromq             conda-forge/linux-64::zeromq-4.3.1-hf484d3e_1000


[Errno 13] Permission denied: '/.cph_tmp28kh1eup'
[Errno 13] Permission denied: '/.cph_tmpwmmrbrfu'

```

Why don't update only dependencies of conda ? Version of conda is kept :+1: 
`$CONDA_DIR/bin/conda update --only-deps conda --quiet --yes `

Thx!

### PR DESCRIPTION
**Pull request by minrk**
gets much faster installs

had to move WORKDIR $HOME up due to tempfile permission issues with conda 4.7 (fixes #891, fixes #878). Conda 4.7 creates some tempfiles in the CWD instead of /tmp (actually conda_package_handling).

### CODE REVIEW

**Comment by parente** [comment]
@minrk Thank you for helping out here while I'm heads down elsewhere.

**Comment by Bidek56** [comment]
This PR seems to break: "conda update", has anyone tried to do: "conda update --yes --all" on the latest image? Thx

**Comment by maresb** [comment]
I wonder if there's a better way than to stop removing qt.  Removing qt reduces the image size from 4.01 GB to 3.68 GB.

If I understand correctly, pyqt is unfortunately an (extraneous?) dependency of matplotlib.  Thus subsequent conda install commands will try to reinstall qt, which is annoying.

I think the ideal solution would be to remove qt and convince conda that it's okay without.  Does anyone know if this is doable?

**Comment by dhirschfeld** [comment]
I think in a container where you don't need the gui front-ends you can install `matplotlib-base` directly rather than `matplotlib` :
```
> conda search --info matplotlib=3.1.1=py37_1

matplotlib 3.1.1 py37_1
-----------------------
file name   : matplotlib-3.1.1-py37_1.tar.bz2
name        : matplotlib
version     : 3.1.1
build       : py37_1
build number: 1
size        : 6 KB
license     : PSF-based
subdir      : win-64
url         : https://conda.anaconda.org/conda-forge/win-64/matplotlib-3.1.1-py37_1.tar.bz2
md5         : fe8dc51d1eff32684a89c08e77934201
timestamp   : 2019-07-24 17:46:41 UTC
dependencies:
  - matplotlib-base 3.1.1 py37h2852a4a_1
  - pyqt
  - python >=3.7,<3.8.0a0
```
i.e. `matplotlib` just repackages `matplotlib-base` plus the `qt` gui toolkit:
```
> conda search --info matplotlib-base=3.1.1=py37h2852a4a_1

matplotlib-base 3.1.1 py37h2852a4a_1
------------------------------------
file name   : matplotlib-base-3.1.1-py37h2852a4a_1.tar.bz2
name        : matplotlib-base
version     : 3.1.1
build       : py37h2852a4a_1
build number: 1
size        : 6.6 MB
license     : PSF-based
subdir      : win-64
url         : https://conda.anaconda.org/conda-forge/win-64/matplotlib-base-3.1.1-py37h2852a4a_1.tar.bz2
md5         : 4e22816c97c10fecee29fa4e05a7884d
timestamp   : 2019-07-24 17:46:01 UTC
dependencies:
  - cycler >=0.10
  - freetype >=2.9.1,<3.0a0
  - kiwisolver
  - libpng >=1.6.35,<1.7.0a0
  - numpy >=1.14.6,<2.0a0
  - pyparsing
  - python >=3.7,<3.8.0a0
  - python-dateutil
  - setuptools
  - tornado
  - vc >=14,<15.0a0
  - zlib >=1.2.11,<1.3.0a0
```

**Comment by parente** [comment]
Thanks for the ref @dhirschfeld. `matplotlib-base` didn't exist when we originally setup the Dockerfile and so we resorted to the uninstall hack.

I'm assuming @minrk recently removed the uninstall to avoid conda environment inconsistencies. I think we should switch to the base package unless my assumption is incorrect.

**Comment by maresb** [comment]
In the context of scipy-notebook, @dhirschfeld's solution works great, so I made the pull request above.

Frustratingly, other conda packages which I want to install later depend on matplotlib instead of matplotlib-base (e.g. geopandas and descartes).  As soon as I installl one of those, I'm unfortunately back in the previous situation.  I should suggest matplotlib-base to the conda maintainers.  Probably I should know this, but it's not clear to me that the package maintainers also maintain their respective conda packages.  Who should I contact?

**Comment by dhirschfeld** [comment]
> *Note to self: I should submit PRs to switch the corresponding feedstocks to matplotlib-base*

I'd strongly encourage you to do so - it'll improve the whole ecosystem :+1:

**Pull request merged**
