### PR TITLE
Temporary workaround for #210

### PR DESCRIPTION
**Pull request by parente**
Pin libjpeg to v8

### CODE REVIEW

**Comment by parente** [comment]
Going to merge this and #238 together to avoid two long builds.

**Comment by jakirkham** [comment]
Thanks for doing this, @parente.

**Comment by jakirkham** [comment]
The build seems to be having connection issues.

**Comment by jakirkham** [comment]
I've tried to restart in hopes that it doesn't have issues this time, but it might be worth checking on later.

**Comment by parente** [comment]
Thanks for restarting @jakirkham 

Pushed `97a5071c5775`.

**Pull request merged**
