### PR TITLE
Add acknowledgement of me :)

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@consideRatio @yuvipanda @manics I would like to ask to have an acknowledgement line for me, so let's have a vote on this, if this is ok. Will only merge if get 3 approvals from you.

**Review by consideRatio — APPROVED** [review]
:heart: :tada: the financial help you have contributed to this project pales in comparison to your care and time contributed to it!!! Thank you @mathbunnyru!!!!!

**Comment by mathbunnyru** [comment]
> ❤️ 🎉 the financial help you have contributed to this project pales in comparison to your care and time contributed to it!!! Thank you @mathbunnyru!!!!!

Thank you! Or, because I celebrate my birthday (which was yesterday) in Paris, merci beaucoup! 😃

**Review by manics — APPROVED** [review]

**Review by yuvipanda — APPROVED** [review]
I would hit merge if I could :)

**Pull request merged**
