### PR TITLE
Clean conda

### PR DESCRIPTION
**Pull request by jakirkham**
Related: https://github.com/jupyter/docker-stacks/issues/62

This cleans out just about everything `conda` can remove. The most notable thing is this removes any unused packages that are lingering.

### CODE REVIEW

**Comment by parente** [comment]
LGTM. Do you want to do the honors of running the manual build on the VM after I merge to get the experience?

**Comment by jakirkham** [comment]
Sure.

**Comment by parente** [comment]
All set. Let me know if anything goes bad in the build. If you start a tmux on the VM, I can pop in later and check it out.

**Comment by jakirkham** [comment]
Ok, should I go ahead and update the debian image?

**Comment by jakirkham** [comment]
Alright, went ahead and updated debian and am running with cache disabled. The tmux session name is release.

**Comment by parente** [comment]
:+1: to updating debian. I think it's the glibc security fix.

If you hit any trouble, just re-run `make release-all` but this time without the cache busting flags. It should pick up right where it left off.

**Comment by jakirkham** [comment]
Sounds good.

**Comment by parente** [comment]
And many thanks for pitching in. Glad to have you on board helping out!

**Comment by jakirkham** [comment]
Thanks. Glad to help.

**Comment by jakirkham** [comment]
Appears there was an issue submitting some of the images. I ran `make release-all`, but it appears that it is still building some images from scratch. It's in the same tmux session.

**Comment by parente** [comment]
I just checked it. Looks like it used cache on all-spark-notebook and the pushes that succeeded. pyspark busted cache for some reason.

**Comment by jakirkham** [comment]
Strange. Thanks for checking. Glad it worked this time.

**Comment by parente** [comment]
It 500'd again trying to push. I watched and this time every docker build sped by as cached and every docker push up to the layer that failed sped by as "Image already exists". It's picking up where it left off again.

This is typical.

**Comment by parente** [comment]
Completed. Webhook updated the build history wiki page with the info.

**Pull request merged**
