### PR TITLE
Print image size after building it

### PR DESCRIPTION
**Pull request by mathbunnyru**
As far as I understand, some people worry about image sizes.
So, I added a simple print statement to make it easier to notice the changes in the logs after building the image.

### CODE REVIEW

**Comment by mathbunnyru** [comment]
So, now it looks like this in CI:

> Successfully built 6206a4265f93
> 977Successfully tagged jupyter/base-notebook:latest
> 978Built image size: 1.13GB

**Comment by romainx** [comment]
Hello @mathbunnyru 

I don't see who you're talking about :sweat_smile:.
More seriously it's a concern for some K8S deployment and people are complaining about the size.
So 👍 for me. It could also be interesting to add the size information in the build manifests that are stored in GitHub wiki pages.

Best.

**Comment by mathbunnyru** [comment]
@romainx thank you for your suggestion.

I tried to add the size info to manifest files.
I don't know how they work and I'm not sure they are checked in CI.

So, please, try to take a look and tell me if something is wrong.

**Comment by parente** [comment]
@mathbunnyru This is a great idea and the changes look right to me. Let's merge and try it.

For your reference, the manifests render as pages over in the GitHub wiki attached to this repo.

https://github.com/jupyter/docker-stacks/wiki

Try clicking "Build manifest" in the right-most column to see a sample.

**Comment by romainx** [comment]
I've just checked and the information in the build manifest is missing.
all_spark_notebook_10c9768598ab_·_jupyter_docker-stacks_Wiki

**Comment by mathbunnyru** [comment]
@romainx @parente thanks for merging, let's now try to make it work :)

Do you know, how can I debug this manifest locally?
Or maybe you can see the logs and say what we should do?

**Pull request merged**
