### PR TITLE
Activate conda base environment by default

### PR DESCRIPTION
**Pull request by jan-janssen**
Some conda packages rely in the `conda activate` to set the corresponding environment variables, therefore just including the `bin` directory in the `PATH` is not sufficient.

### CODE REVIEW

**Review by romainx — CHANGES_REQUESTED** [review]
Hello,

Thanks for submitting this PR. You're right, there is definitely something to do and I think it's summarized in #1086. However I'm not sure about the way to do it. What you have done is to overwrite the `~/.profile`. This solution could cause problem in certain contexts where users provide their own profile through bind mount or when running these images in K8s. 

I do not have the solution at the time of writing however, I do not think we will merge this PR as is.
If you have a better solution, feel free to propose it.

Best

**Comment by jan-janssen** [comment]
The alternative option would be adding it directly to `/etc/profile` as that should be loaded before any user specific files are loaded.

**Comment by romainx** [comment]
Another option, more consistent with what is already done, is to add the content generated by the command `conda init bash` in the `.bashrc` skeleton `/etc/skel/.bashrc`. It is already customized in the image.

https://github.com/jupyter/docker-stacks/blob/612aa5710bf9f9394a6b108cda6cbbc88f41f924/base-notebook/Dockerfile#L56-L57

This [SO answer](https://stackoverflow.com/a/58081608/4413446) gives an alternative that could be interesting in our case.

Here is the change to perform.

```diff
# Enable prompt color in the skeleton .bashrc before creating the default NB_USER
+ # hadolint ignore=SC2016
- RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc
+ RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc && \
+    # Add call to conda init script see https://stackoverflow.com/a/58081608/4413446
+    echo 'eval "$(command conda shell.bash hook 2> /dev/null)"' >> /etc/skel/.bashrc 
```

Once added, the `base` environment is activated by default and the variables are set.

```bash
$ docker run -it --rm  jupyter/base-notebook bash

(base) jovyan@c3ee08cdc4ff:~$ env | grep -E '(CONDA_DIR|CONDA_PREFIX)'
CONDA_PREFIX=/opt/conda
CONDA_DIR=/opt/conda
```

Could you please try to implement it this way and check if it answers your needs?

Many thanks

**Comment by jan-janssen** [comment]
@romainx That is a great suggestion - it works for me, so I updated the pull request accordingly.

**Review by romainx — APPROVED** [review]

**Comment by romainx** [comment]
@jan-janssen thanks for the feedback.
@parente I have contributed to the solution, si I would like to have your opinion before merging this PR.
Many thanks.

**Pull request merged**
