### PR TITLE
Upgrade to Jupyter Notebook 4.0

### PR DESCRIPTION
**Pull request by parente**
* Change minimal-notebook to install notebook=4.0*
* Change config and pem file paths for jupyter 
* Install ipywidgets in all containers that have a Python stack
* Update all READMEs to describe v3.2 and v4.0 since Docker Hub only shows one README for all tags

Doing this all in a 4.0.x branch first to check how it builds on Docker Hub under a 4.0 tag. If all goes well, will merge to master here and latest there.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Ok, sweet. Will this be the right one for us to base `jupyter/demo` off, or one of the other stacks?

**Comment by parente** [comment]
> Will this be the right one for us to base jupyter/demo off, or one of the other stacks?

The jupyter/minimal-notebook? I guess we could rebase the demo image on it, but it lacks the branding, CSP config, etc. that are in the current jupyter/minimal. Those will need to move into the demo image itself.

**Comment by rgbkrk** [comment]
We can always move the config step to *after* the installation steps. Most of that old ordering was about caching order for my own sanity during dev builds.

**Comment by parente** [comment]
That sounds fine. So how about:

1. this goes in as the 4.0 branch
2. we do all the work to get that tag building and then rebase master on it (i.e., complete issue #14)
3. we open / work the issue against docker-demo-images to rebase that repo on jupyter/minimal-notebook:4.0 once it hits Docker Hub.

If PR #13 goes into master before (2) above completes, we'll need to bring it up to 4.0 also. If it goes in after, we'll need to merge it against the 3.2.x branch instead and then bring it up to 4.0. And regardless of order, it needs to go into the 3.2.x branch anyway for stable builds against that version.

**Comment by rgbkrk** [comment]
1. :white_check_mark: 

I'm going to leave #13 decisions up to you.

**Comment by rgbkrk** [comment]
To save yourself headaches, you may find adapting to only 4.0.x to be easiest (since config files should stay in the same place), but not all kernels are adapted. :confused:

**Pull request merged**
