### PR TITLE
Update old distro codename

### PR DESCRIPTION
**Pull request by jakirkham**
Update from `wheezy` to `jessie`. It's possible there is a reason this is still `wheezy`, in which case it would be nice to know what it is. If not, we should probably update them.

Maybe we should hard code these as environment variables in the base image and those variable will carry through to here. Thoughts?

### CODE REVIEW

**Comment by parente** [comment]
The mesos packages were not available in jessie when I last tried. That's why I had to pull them from wheezy.

**Comment by jakirkham** [comment]
Ah, ok. Let me check.

**Comment by jakirkham** [comment]
Yeah, still not present. I'll close this out.

**Comment by parente** [comment]
If you want to put in a PR to add a comment in the Dockerfile so I / we don't forget again, we can merge that.

**Comment by jakirkham** [comment]
How about an issue? That way it will be a little more visible. Though we can of course have the comment too.

**Comment by parente** [comment]
Sure. Issue is fine also.

**Comment by jakirkham** [comment]
Issue is opened here ( https://github.com/jupyter/docker-stacks/issues/137 ). PR is opened here ( https://github.com/jupyter/docker-stacks/pull/138 ).

**Pull request closed without merging**
