### PR TITLE
Julia v0.6.2

### PR DESCRIPTION
**Pull request by ellisvalentiner**

### CODE REVIEW

**Comment by parente** [comment]
The build failed due to a JupyterLab extension incompatibility, nothing related to this PR.  I just merged #508 which has that fix. I'll retry the build here to make sure it's clean.

**Comment by parente** [comment]
@ellisvalentiner Could you please rebase your PR on master so we can get a clean build/test run? Thanks!

**Comment by ellisvalentiner** [comment]
@parente after rebasing I had to update the domain name. Sorry for the extra noise.

**Comment by parente** [comment]
No problem. Looks good now. Merged!

**Pull request merged**
