### PR TITLE
Refactor logging in start.sh and add JUPYTER_DOCKER_STACKS_QUIET

### PR DESCRIPTION
**Pull request by maresb**
Cherry-pick of 63295ba, working through  https://github.com/jupyter/docker-stacks/pull/1512#issuecomment-962672049

> It is meant to allow you to opt out from non-error non-warning logs
> generated by start.sh.

### CODE REVIEW

**Review by mathbunnyru — APPROVED** [review]
Looks awesome:

Possible future improvements (just a note for someone, who will want to improve our docker stacks):
1. Always add log_level like this: `_log "INFO" "my_message"
2. Based on log level color can be added.
3. Exit on fatal errors (or maybe just errors)
4. Add timestamps, like `INFO[2021-08-23 11:00:00.000000] my_message`
5. Stop using `bash`, haha 👍 

@maresb maybe you could add a test for this variable?

**Comment by mathbunnyru** [comment]
@maresb 
I added an issue to improve log function, I think, if you added a test, then it would be perfect.
Another thing to add is a line-or-two of documentation.

**Comment by maresb** [comment]
> 5. Stop using `bash`, haha :+1:

:arrow_up: :heavy_check_mark:  :arrow_up: :heavy_check_mark:  :arrow_up: :heavy_check_mark: 

I'm convinced that this right here is the root of most of our problems.

If we get a comprehensive test suite for `start.sh` running, I think it'd be a piece of cake to introduce #1233 and bring it up to feature parity. Once we're convinced it's reliably working, then ditch `start.sh` and maintenance and features become *so* much easier and more sane.

**Comment by maresb** [comment]
Hmm, seems to be a CI error, I'll restart.

**Comment by mathbunnyru** [comment]
@maresb @consideRatio I gave this a thought - do we really need JUPYTER_DOCKER_STACKS_QUIET?
I think this script generates only a couple of lines of logs in the worst case and it's not a big deal.

I personally think it's easier to remove this variable and merge this PR without adding a test case.
If someone will need this variable, then we will gladly accept the PR in the future.

**Comment by consideRatio** [comment]
I recall adding it initially because there was some noise about "if this emits logs, it means my automation runs into trouble that parses the output" or similar. I've lost track of the change motivation at this point, but I recall it wasn't stemming from solving a problem of my own.

**Comment by mathbunnyru** [comment]
I updated the issue, let's merge this 👍

**Pull request merged**
