### PR TITLE
Rename: ROOT_CONTAINER->ROOT_IMAGE, BASE_CONTAINER->BASE_IMAGE

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Describe your changes

There is no such thing as parent (base/root) container, it's about images, so let's use proper naming

## Issue ticket if applicable

Fix: https://github.com/jupyter/docker-stacks/issues/2154

## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
This is not breaking if you simply run one of our images or use it as a parent image.
But it might be breaking for people who build custom set of images - I think they are advanced users and it's ok to break small things sometimes, they can fix the problem easily.

**Comment by manics** [comment]
What might be nice is to have a (sort of) changelog page, but rather than being comprehensive it only has major/breaking changes along with the date? This could also be a nice place to highlight the planned update to Python 3.12.

**Comment by mathbunnyru** [comment]
> What might be nice is to have a (sort of) changelog page, but rather than being comprehensive it only has major/breaking changes along with the date? This could also be a nice place to highlight the planned update to Python 3.12 when it's made.

Done, please, take a look

**Comment by mathbunnyru** [comment]
https://github.com/jupyter/docker-stacks/blob/15f39abfed925a6ee89954ccd968777372ce346b/CHANGELOG.md

**Review by manics — APPROVED** [review]

**Pull request merged**
