### PR TITLE
Use spark-1.5.1

### PR DESCRIPTION
**Pull request by zaxariah**
Small change to update to Spark 1.5.1. So far, in my own code and testing, this has worked fine.

### CODE REVIEW

**Comment by parente** [comment]
Thanks for it. I'll get on figuring out how to version these dependencies so that users of the current 1.4.1 image can continue to pull the old container image. Then we can merge this and make it latest.

**Comment by parente** [comment]
Ref #26

**Comment by parente** [comment]
Can you update the all-spark-notebook with the same change and make a note in both READMEs of the Spark version number?

**Comment by depend** [comment]
I update Dockerfile and README.md in both all-spark-notebook and pyspark-notebook.  https://github.com/jupyter/docker-stacks/pull/52

**Comment by parente** [comment]
Awesome. Thank you. Will give that PR a quick build sniff test later and then merge.

**Pull request closed without merging**
