### PR TITLE
Use another repo for prettier pre-commit

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Describe your changes

https://github.com/prettier/prettier/issues/15742

## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
Merged this, seems to work fine, and it will stay up-to-date.

**Comment by manics** [comment]
Thanks for finding this, it's been bothering me for a while in other repos 😃

**Comment by mathbunnyru** [comment]
> Thanks for finding this, it's been bothering me for a while in other repos 😃

Glad to help, it has been bothering me as well 🙂 

Note: this is not an official way to use prettier as a pre-commit hook, but there is no longer an official way at all (the official repo was archived).
But I consider the fork to be good enough and I don't expect any problems.
If `prettier` or `pre-commit` decide to implement an official way of using one with another, I will of course switch to it.

**Comment by mathbunnyru** [comment]
Btw, the issue with having `node_modules/` in every repo with this hook seems to be fixed: https://github.com/rbubley/mirrors-prettier/pull/2

**Pull request merged**
