### PR TITLE
Add image with Linux Desktop environment in it

### PR DESCRIPTION
**Pull request by yuvipanda**
The JupyterHub project's
[jupyter-remote-desktop-proxy](https://github.com/jupyterhub/jupyter-remote-desktop-proxy) has been getting a bunch of good use lately, particularly around bringing users who wouldn't traditionally use notebooks *alone*. For example, in this climate science workshop's blog post on the jupyter
blog (https://blog.jupyter.org/desktop-gis-software-in-the-cloud-with-jupyterhub-ddced297019a?postPublishedType=initial), you can see how being able to use *both* notebooks and linux desktop software (qgis, in this case) in the same way brings an entirely new class of users to the Jupyter ecosystem.

However, running this linux desktop environment inside a container isn't particularly easy, and getting a base image running will be useful to a lot of people. I can provide links to different communities that this would benefit if needed.

This PR adds such a base image that others may inherit from to add specific packages on top. If this looks good, I can write up documentation on how to add specific images - and we can use qgis as a good example.

## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by consideRatio** [comment]
This project hasn't added images for a long time, but during the last few months, this has changed. I see that as enabled by an amazing effort by @mathbunnyru helping the project catch up on a huge amount of maintenance.

To ensure healthy maintenance of this project, I consider its crucial that the issue about defining an image policy in #1958 is completed before this PR is considered.

**Comment by bjornjorgensen** [comment]
why don't you use [KasmVNC](https://kasmweb.com/kasmvnc) ? 
linuxserver.io does use it.

**Comment by freitagb** [comment]
Thanks for raising this point @yuvipanda - this kind of feature would be extremely helpful for the U.S. Greenhouse Gas Center jupyterhub we're currently deploying.

**Comment by yuvipanda** [comment]
@bjornjorgensen mostly because tigervnc is where all the current experience has been. I think there are definitely many other options to explore.

**Comment by consideRatio** [comment]
Having reasoned about this further I think that jupyter/docker-stacks shouldn't (at least not yet) embrace a new image including [jupyter-remote-desktop-proxy](https://github.com/jupyterhub/jupyter-remote-desktop-proxy) together with system level dependencies to present and remote view a Linux desktop user interface.

I reason that adding an image like this is similar to adding a new image for a another programming language besides what the project currently maintain images for (Julia, Python, R). Doing that would introduce a new set of complexities for this projects maintainance.

Practically for this specific image, I think it could pivot towards the jupyterhub/jupyter-remote-desktop-proxy project's [existing Dockerfile](https://github.com/jupyterhub/jupyter-remote-desktop-proxy/blob/main/Dockerfile#L1). It currently builds on the jupyter/base-image already.

Sorry for pushing back on this @yuvipanda, I'm very happy to help work this in jupyterhub/jupyter-remote-desktop-proxy though!

**Comment by yuvipanda** [comment]
I am pretty happy with that resolution, @consideRatio! I think that would also allow us to offer more variants, including an image with qgis pre-installed perhaps! I'll close this one, and move it over there.

**Comment by benz0li** [comment]
FYI @yuvipanda 

* [b-data/jupyterlab-qgis-docker-stack](https://github.com/b-data/jupyterlab-qgis-docker-stack)
* [pangeo-data/jupyter-earth](https://github.com/pangeo-data/jupyter-earth)
* [geocompx/docker](https://github.com/geocompx/docker)

**Comment by yuvipanda** [comment]
Thank you very much for those links, @benz0li! I appreciate those.

I'm currently the maintainer of the jupyter-earth image, and my hope is to eventually split that image up into many different ones. This would be one of them. 

The other images are all super cool! I think I'd like to base one off the jupyter dockerstacks one, and use mamba in general rather than apt. But lots of XFCE stuff for me to reuse (and I'll make sure to credit appropriately).

I've moved this one to https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/51, and expanded it to include a qgis specific image as well. 

Thank you for the discussion, @consideRatio!

**Pull request closed without merging**
