### PR TITLE
Upgrade `Python` to 3.11

### PR DESCRIPTION
**Pull request by bjornjorgensen**
## Describe your changes
Upgrade PYTHON_VERSION from 3.10 to 3.11
## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [x] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by benz0li** [comment]
Regarding `scipy-notebook`:
*  `numba` does not yet support Python 3.11.
*  The current release of `pytables` and `statsmodels` do not build with Python 3.11.
    *  Both packages build from branch main, though.

Cross references:

* https://github.com/numba/numba/issues/8304
* https://github.com/PyTables/PyTables/issues/954
  * https://github.com/PyTables/PyTables/pull/962
* https://github.com/statsmodels/statsmodels/issues/8287
  * https://github.com/statsmodels/statsmodels/pull/8431

**Comment by mathbunnyru** [comment]
Please, also change the python version in tests.

**Comment by bjornjorgensen** [comment]
Thank you @benz0li and @mathbunnyru 
I found one test that I have changed the python version to 3.11

**Comment by bjornjorgensen** [comment]
hmmm... it failed with some strange errors

#14 12.04 Encountered problems while solving:
#14 12.04   - package mamba-0.18.1-py310hcf12e44_1 requires python_abi 3.10.* *_cp310, but none of the providers can be installed


#15 24.31 error    libmamba Could not solve for environment specs
#15 24.31 Encountered problems while solving:
#15 24.31   - package mamba-0.0.10-py27hc9558a2_1 requires python >=2.7,<2.8.0a0, but none of the providers can be installed


But where does this old mamba come from?

**Comment by bjornjorgensen** [comment]
@mathbunnyru Yes, that it a good idea.

**Comment by EwoutH** [comment]
Statsmodels [0.13.3](https://github.com/statsmodels/statsmodels/releases/tag/v0.13.3) is released, with Python 3.11 wheels!

**Comment by bjornjorgensen** [comment]
@EwoutH yes, but [When should you upgrade to Python 3.11?](https://pythonspeed.com/articles/upgrade-python-3.11/) so will wait for 3.11.1 and everything else that we have are supported in python 3.11

**Comment by bjornjorgensen** [comment]
https://github.com/jupyter/docker-stacks/pull/1815

**Pull request closed without merging**
