### PR TITLE
Introduce policy to update python version

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@bjornjorgensen please take a look

**Review by bjornjorgensen — APPROVED** [review]

**Comment by bjornjorgensen** [comment]
When a new major `Python` version

add major?

**Comment by mathbunnyru** [comment]
> When a new major `Python` version
> 
> add major?

I'm not sure what is the correct name for Python versioning (because I think `3` is a major version).

**Comment by benz0li** [comment]
> I'm not sure what is the correct name for Python versioning

I am confident Python uses [Semantic Versioning](https://semver.org): `MAJOR.MINOR.PATCH`

**Comment by manics** [comment]
Python doesn't use semantic versioning. For example, these breaking changes were made in 3.10:
https://docs.python.org/3/whatsnew/3.10.html#removed

**Comment by mathbunnyru** [comment]
Thanks @manics. I guess I will keep this PR as it is then.
Could you please share your opinion on this policy?

**Comment by manics** [comment]
From a technical perspective, it sounds fine to me.

From a user perspective- that depends on your goals.
https://jupyter-docker-stacks.readthedocs.io/en/latest/#using-old-images
Do you see this project as leading the way, and encouraging users to use a particular version of Python? Or do you want to be more responsive to users, which means gathering feedback from e.g. https://discourse.jupyter.org/ to gauge the general feeling on which Python should be supported and when a switch should be made?

**Comment by benz0li** [comment]
> Python doesn't use semantic versioning.

Agreed: https://peps.python.org/pep-0440/

**Comment by mathbunnyru** [comment]
> From a technical perspective, it sounds fine to me.
> 
> From a user perspective- that depends on your goals. https://jupyter-docker-stacks.readthedocs.io/en/latest/#using-old-images Do you see this project as leading the way, and encouraging users to use a particular version of Python? Or do you want to be more responsive to users, which means gathering feedback from e.g. https://discourse.jupyter.org/ to gauge the general feeling on which Python should be supported and when a switch should be made?

I would like to find a good balance between switching too early and switching too late.
With a similar Ubuntu policy, I didn't see any negative feedback, which is nice.

I guess, this policy will also make it clear for our users when we will support the new python version and they won't actually have to wait for a long time after a release (around 2 months I suppose).
At the same time, we have never deleted old images, so users, who want to stick with them, can do it.

**Pull request merged**
