### PR TITLE
Added ubuntu:14.04 locale fix

### PR DESCRIPTION
**Pull request by jakirkham**
Sorry this is way overdue. Added locale fixes for ubuntu:14.04 so that we can get CI running as was mentioned here. ( https://github.com/jupyter/notebook/pull/547#issuecomment-146991682 )

Circle CI seemed like the best choice for doing CI with docker images. However, they did not allow us to change the locale. Not changing the locale caused us build issue with the `jupyter/notebook` image. Changing locale is not a problem when building on Docker Hub or locally. The image described here simply applies the needed locale change so it can act as a base image for `jupyter/notebook` and allow for CI support on that image.

ping: @parente

### CODE REVIEW

**Comment by parente** [comment]
This is the first image definition that doesn't fall into the category of pull-and-run for end users. If there's no better place, people can ignore it, of course. But putting it down in a subfolder like `internal` or something similar so it's not at the top level like the others would help.

@minrk @rgbkrk any alternatives or is this the spot?

**Comment by jakirkham** [comment]
Putting it in a lower directory is fine. Keeping it as a separate repo could be fine. Simply up to you guys. Just let me know.

**Comment by rgbkrk** [comment]
Is it bad if this is in the main image and people have to overwrite the env var for their locale?

**Comment by jakirkham** [comment]
Shouldn't be. Should be trivial for anyone to change. Though adding UTF8 as the default is probably a good idea anyway or is that why you are asking?

**Comment by rgbkrk** [comment]
Let's kick this off! Thank you @jakirkham for keeping up with these.

**Comment by parente** [comment]
Er, so I'll move it down to a subdir and kick off a built. Maybe a separate make target because we don't want to rebuild it every time we do the other stacks, right?

**Comment by parente** [comment]
@jakirkham what do you want the image called on Dockerhub so that the jupyter/notebook Dockerfile can refer to it?

**Comment by rgbkrk** [comment]
Thanks @parente

**Comment by jakirkham** [comment]
Obviously I am not keeping up enough. ;)

Maybe it can be `ubuntu_14_04_locale_fix`. It's a bit verbose, but it does get the point across. If you can think of a better name, feel free to pick one. It would be nice that the directory and the docker image share the same name though.

**Comment by parente** [comment]
All set: https://hub.docker.com/r/jupyter/ubuntu_14_04_locale_fix/

**Comment by jakirkham** [comment]
Cool, thanks. FWIW, my Docker Hub handle is the same as my GitHub one.

**Pull request merged**
