### PR TITLE
Try to fix port for jupyterhub

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Issue ticket if applicable

Fix: https://github.com/jupyter/docker-stacks/issues/1862

## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@twalcari could you please check this change fixes it for you?

**Comment by mathbunnyru** [comment]
@consideRatio I would like to point out that running our docker images under jupyterhub are not tested at all in this repo.
Do you know what would be the best way to test it (maybe you have some minimal jupyterhub example) and in which repo should we test it?

**Comment by twalcari** [comment]
Hi, I've been able to narrow it down this morning to the `JUPYTERHUB_SERVICE_URL`.

My custom spawner did not implement a value for `port`, which caused it to default to 0. This resulted in the following `JUPYTERHUB_SERVICE_URL`: `http://127.0.0.1:0/user/twalcari@ilabt.imec.be/`

After adding the following lines to my spawner, the JUPYTERHUB_SERVICE_URL is now `http://127.0.0.1:8888/user/twalcari@ilabt.imec.be/` and the problem is gone.

```python
class GPULabSpawner(Spawner):
    ...

    @default("port")
    def _default_port(self):
        return 8888

```

I would suggest failing the startup of the docker container if such an invalid URL is received with an informative error would be better than this strange behavior of the port changing to 80 😅

**Comment by mathbunnyru** [comment]
I guess we should still use the port set in JUPYTER_PORT, shouldn't we?
I don't completely understand what behaviour we should implement (and users expect).

**Comment by twalcari** [comment]
> @consideRatio I would like to point out that running our docker images under jupyterhub are not tested at all in this repo. Do you know what would be the best way to test it (maybe you have some minimal jupyterhub example) and in which repo should we test it?

I was a bit stuck wrt to testing this yesterday because the startup script hangs if it is unable to reach the JupyterHub service. After analyzing the traffic, I determined that the Jupyter process in the docker container does not use the result of the HTTP-requests it does to the hub.

My solution was to launch a small webserver which just reacts with 200 replies to all requests. I used the example from: https://gist.github.com/bradmontgomery/2219997

**Comment by twalcari** [comment]
> I guess we should still use the port set in JUPYTER_PORT, shouldn't we? I don't completely understand what behaviour we should implement (and users expect).

After a bit of searching, it seems like the answer is in `notebook/notebookapp.py`, cfr. https://github.com/jupyter/notebook/pull/5221

I don't think that the fix you committed earlier is needed because of this. It also won't solve the bug uncovered in this issue as it is related to a faulty(?) `JUPYTERHUB_SERVICE_URL`

**Comment by manics** [comment]
My guess for testing JupyterHub (untried, but I might give it a go if I have time) is probably to copy a test from DockerSpawner:
- conftest: https://github.com/jupyterhub/dockerspawner/blob/8503af69161a3a543cc613f93ce7951ad30a1912/tests/conftest.py#L59-L84
- start/stop test https://github.com/jupyterhub/dockerspawner/blob/8503af69161a3a543cc613f93ce7951ad30a1912/tests/test_dockerspawner.py#L42-L61

Longer term https://github.com/jupyterhub/pytest-jupyterhub may avoid the need to copy conftest, you'd still need a spawner implementation though

**Comment by mathbunnyru** [comment]
Ok, I guess I will close this PR and thee issue (because there is an upstream issue).

**Pull request closed without merging**
