### PR TITLE
Clean apt-get list

### PR DESCRIPTION
**Pull request by jakirkham**
Related: https://github.com/jupyter/docker-stacks/issues/62

Simply empties `/var/lib/apt/lists/` of contents. This directory is repopulated on any call to `apt-get update` so it is not a problem to remove it. All it serves as is a cache. Should save a little bit more space for each image (~10MB).

Refs:
* ( http://unix.stackexchange.com/a/217371 )
* ( http://askubuntu.com/questions/179955/var-lib-apt-lists-huge-in-12-04/179992#179992 )

### CODE REVIEW

**Comment by jakirkham** [comment]
Will squash once we are happy with it.

**Comment by jakirkham** [comment]
Exceeded build time during the first build. Expect this will continue as it is building all the images, which I think is just outside Travis CI's time limit.

**Comment by jakirkham** [comment]
To give some idea of the effects, the `minimal-notebook` will be reduced by `~10 MB` and the `datascience-notebook` will be reduced by `~50 MB`. These aren't exactly massive savings, but they are easy to get. Images that use `apt-get` in many `RUN` steps will likely benefit more than those that don't.

**Comment by DrPaulBrewer** [comment]
Just remember that because of docker layering, a "RUN apt-get clean" on its
own line still stores all the old files from the previous line in an
internal layer.

I'm sure you know that already, and are being careful, but not everyone is
aware of the consequences of docker's layering.

**Comment by jakirkham** [comment]
I am aware. I don't think I add such a line. Do you see some?

**Comment by DrPaulBrewer** [comment]
No, it was a knee-jerk reaction. I'm trying to concentrate on two other
things at same time.

**Comment by jakirkham** [comment]
Failed again due to reaching max time limit.

@parente, do you have any thoughts on this? It appears to be working fine we are just running into time limit issues.

**Comment by parente** [comment]
I'm fine with the change. Want to squash it before merge?

**Comment by jakirkham** [comment]
Squashed and rebased on master. Don't think there is any point in waiting for the tests as they will just time out again, but I will leave it in your hands.

**Comment by jakirkham** [comment]
Thanks.

**Comment by jakirkham** [comment]
Building on tmux release. Decided to build because we don't want these additional cleaning steps interfering with running CI.

**Comment by parente** [comment]
Sure. Build whenever you think it's time. It's a pretty stress free process. Either it completes, or it doesn't and you re-run.

**Pull request merged**
