### PR TITLE
Add a Jupyter data science notebook stack

### PR DESCRIPTION
**Pull request by nymoorland**
@parente A combined Dockerfile of scientific Python and R is useful for us data geeks. This built and ran successfully locally. Please free to edit or add to it. These stacks are great, thanks.

### CODE REVIEW

**Comment by parente** [comment]
Thanks for the pull request. Other than size of the image, do you think there's a significant difference between this image and the all-spark-notebook which has Python, R, and Scala plus their Spark libraries preconfigured? Would Python, R, and Julia be a more useful datascience-notebook stack?

I'm considering how to balance the minor variations on stacks with the number of images needing to be maintained.

**Comment by nymoorland** [comment]
Oh thanks, I had not taken a look at that notebook. I agree with you that it's better to keep the variations to a minimum along with deciding what libraries go into them because it's so subjective.

The Spark notebook certainly fits the need for having both Python and R. Julia,Python, and R would be useful as a data science stack and I'm guessing that the image would be much smaller sans Scala dependencies. 

I really like the idea of the Jupyter docker stacks as a base or minimal stack. I've already found them to be useful.

**Comment by parente** [comment]
> Julia,Python, and R would be useful as a data science stack and I'm guessing that the image would be much smaller sans Scala dependencies.

I think @ellisonbg requested this stack too. If you're interested in "tuning up" this merge request to include Julia as well, please do so. (I believe the jupyter/docker-demo-image has Julia installed so it's probably some copy/paste work.) If not, I was planning on creating such a stack eventually and can do it if you don't have the cycles.

**Comment by ellisonbg** [comment]
I do think a data science stack would be useful, but don't see why Scala
wouldn't be included. The difficulty of composing these things still stands
out as an unsolved problem to me. Any new thoughts on that front? I think
the main approaches are:

* Build a separate toolchain for composing docker build files as text files.
* Start to build docker images that only include a single kernel that can
be composed at a higher level with the jupyter message arch.



On Sat, Aug 22, 2015 at 5:30 PM, Peter Parente <notifications@github.com>
wrote:

> Julia,Python, and R would be useful as a data science stack and I'm
> guessing that the image would be much smaller sans Scala dependencies.
>
> I think @ellisonbg <https://github.com/ellisonbg> requested this stack
> too. If you're interested in "tuning up" this merge request to include
> Julia as well, please do so. (I believe the jupyter/docker-demo-image has
> Julia installed so it's probably some copy/paste work.) If not, I was
> planning on creating such a stack eventually and can do it if you don't
> have the cycles.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/docker-stacks/pull/13#issuecomment-133767167>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by parente** [comment]
> Start to build docker images that only include a single kernel that can be composed at a higher level with the jupyter message arch.

@rgbkrk shared his thoughts on this approach with me. It sounds like a reasonable experiment to try.

From my experience with launching remote kernels from Jupyter Notebook, I think it minimally involves modifying the code paths back from the notebook frontend to the kernel manager to include more than a kernel name (e.g., URI of a provisioner). It might also require a discovery mechanism beyond process-based kernel specs if the notebook server image is to remain untouched when new kernel containers become available.

Tactically, I think a Python, R, Julia image is a reasonable addition to what docker-stacks has, if only for the reason that Julia is no where to be found yet, while Scala is available in the all-spark-notebook image.

**Comment by minrk** [comment]
Probably didn't mean to include the '~' file. Do you want to add that suffix to .gitignore if it isn't there already?

**Comment by nymoorland** [comment]
> If you're interested in "tuning up" this merge request to include Julia as well, please do so.

@parente Sure, I can add Julia into the Dockerfile for the merge request. Will submit that soon.

>Probably didn't mean to include the '~' file. Do you want to add that suffix to .gitignore if it isn't there already?

@minrk Good catch. Will update the .gitignore with the updated merge request.

**Comment by nymoorland** [comment]
Julia has been added. I'll update it to 4.0 once the minimal image is available in the hub to test the build locally. Why git is ignoring my gitignore?

**Comment by parente** [comment]
You probably need to `git rm` the ~ files you already committed. AFAIK, the ignore only takes effect on files that aren't already version controlled.

**Comment by nymoorland** [comment]
Thanks! 

@parente (I read your recent article. You are working on some really cool stuff that I'm interested in. Will touch base with you on that later). Cheers.

**Comment by parente** [comment]
@nymoorland Thanks for cleaning up this pull request. You submitted it in the middle of my working to get the 4.0 images built and making those the "latest" tagged images on Docker Hub. I'd like to finish off that work first before testing and merging your work. 

My thinking is that as new stacks appear, we should only spend time on rolling the forward, not trying to backport them onto older version of Jupyter unless there's a real reason to do so. In this case, the only reason I can think of is if Julia kernel is not yet 4.0 compliant (but I suspect it is.)

Any reservations about this plan?

PS - Glad to chat with you about whatever else on the mailing list or gitter or email or ...

**Comment by nymoorland** [comment]
@parente Sounds good to me. Thanks.

**Comment by parente** [comment]
master/latest is now 4.0 based per issue #6. I plan on testing this today locally. If all goes well, will merge.

**Comment by nymoorland** [comment]
Super! :+1: :cake:  Once again, thanks for putting these stacks together.

**Comment by parente** [comment]
Started on this, which lead me to #17. Instead of introducing another ha-ha-not-really-4.x build into the fray, going to delay on this.

If you need it ASAP, you can resubmitted against the 3.2.x branch and we can get it going there.

**Comment by nymoorland** [comment]
Sure, no hurry:) I don't need it personally. Sorry you are finding so many issues. I guess that's the nature of the beast. Thanks for the update though.

**Comment by parente** [comment]
I tacked on a commit on to your work in PR #19 so that it works against notebook 4.0.x. Thanks again for the contribution @nymoorland.

**Pull request closed without merging**
