### PR TITLE
Remove emacs and jed from the minimal image

### PR DESCRIPTION
**Pull request by mathbunnyru**
Fix https://github.com/jupyter/docker-stacks/issues/1174

### CODE REVIEW

**Comment by romainx** [comment]
Thanks @mathbunnyru and goodbye old friends 😄 

However @parente was not in favor of removing jed at least.
> #121 (comment) talks about why jed was proposed and added. Do we gain much by removing it?

Sorry I should have mentioned it in the issue #1174
So I let him approve it or not. If it's not approved we will close the corresponding issue.

Thanks. again

**Comment by parente** [comment]
I've been on the fence about removing `jed` since it takes up very little space, is stable, and offers new users a basic editing experience. I also see the argument for making the "minimal" image smaller, removing overlapping tools, and focusing on Jupyter tools with other software playing a supporting role. I think the latter mindset is consistent with the recent project trajectory, and so I'm OK with merging this PR and removing both editors.

One question: if someone submits a PR removing vim, will we be consistent and accept it?

**Comment by romainx** [comment]
@parente the war between emacs and vim is never over 🤣 
- **My official answer**: Yes but we have to keep at least a minimal editor to perform basic tasks in the terminal say choosing between vim and nano. :innocent:
- **What I am thinking**: NO! :scream:

**Comment by mathbunnyru** [comment]
@parente hopefully, it's not my choice to make 🤣 (I am not a maintainer)

I would personally argue against deleting vim - it makes it more difficult to debug these images when you don't have tools at all.
So, yeas, as @romainx said, it's nice to have at least a minimal editor.

**Pull request merged**
