### PR TITLE
Upgrade to the first JupyterLab beta v0.31

### PR DESCRIPTION
**Pull request by chriszs**

### CODE REVIEW

**Comment by parente** [comment]
The initial test failures are unrelated to the version update. (Looks like the docker-py API changed and is now returning JSON instead of a simple int in the wait calls.)

Even though the build has not made it that far yet, I think the version of the jupyter widgets lab extension in scipy-notebook also needs to change.

**Comment by chriszs** [comment]
Okay. Thanks! Looks straightforward to update the tests. I'll try that now.

**Comment by parente** [comment]
@chriszs Sweet. Thanks for taking a crack at the tests. If you hit unexpected problems, just shout.

**Comment by parente** [comment]
Ref: Release notes from the release 4 days ago. The `wait` API change is mentioned as returning a dict. https://github.com/docker/docker-py/releases/tag/3.0.0

**Comment by parente** [comment]
Looks good now. Thanks for the updates @chriszs . 🍰

**Pull request merged**
