### PR TITLE
Add note for launching notebook with no token

### LINKED ISSUE #728: Feature: start.sh jupyter lab --secured-env
Hi,
**Thank you for all the effort making the Jupyter Docker Stacks.**

The default security is very good.

There are use cases, encouraged by containers, where the jupyter container and the system it runs within, lie inside the security boundary.

In these use cases it is convenient to have a command line option to launch the server without password or token.

Currently my chef recipe launches jupyter lab as follows:

```ruby
docker_container 'jupyter-datascience' do
  repo 'jupyter/datascience-notebook'
  tag '1145fb1198b2'
  port '80:8888'
  env 'JUPYTER_ENABLE_LAB=yes'
  volumes [ "/home/#{node[:user][:username]}/work:/home/jovyan/work" ]
  command 'start.sh jupyter lab'
  action :run
end
```

It would be useful to launch the jupyter lab container with no password and no token by: 

**`start.sh jupyter lab --secured-env`**

### PR DESCRIPTION
**Pull request by ericdill**
Closes #728 

Hi @taqtiqa-mark -- Can you read through this and give me feedback on how well I represented your use case?

### CODE REVIEW

**Comment by ericdill** [comment]
@parente this build actually finished but the travis-ci hook either didnt fire or got ignored by github.

**Comment by parente** [comment]
Thanks. Waiting a few days to see if @taqtiqa-mark has any feedback before merging.

**Comment by taqtiqa-mark** [comment]
@ericdill, thanks.  Looks perfect to me.

**Comment by parente** [comment]
Thanks @ericdill!

**Pull request merged**
