### PR TITLE
Bump Spark to 1.6.1, Toree to 0.1.0.dev6

### LINKED ISSUE #169: Is SPARK_OPTS really effective?
I tried to set the JVM options by using `SPARK_OPTS`, but I didn't find any evidence of usage of this environment variable. To check the container's JVM options, I did a `cat /proc/JVM-PID/cmdline` inside the container and I got this:

> /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java-cp/home/jovyan/drivers/postgresql-9.4.1208.jre7.jar:/usr/local/spark/conf/:/usr/local/spark/lib/spark-assembly-1.6.0-hadoop2.6.0.jar:/usr/local/spark/lib/datanucleus-api-jdo-3.2.6.jar:/usr/local/spark/lib/datanucleus-core-3.2.10.jar:/usr/local/spark/lib/datanucleus-rdbms-3.2.9.jar**-Xms1g-Xmx1g**-XX:MaxPermSize=256morg.apache.spark.deploy.SparkSubmitpyspark-shell

Since we have `--driver-java-options=-Xmx4096M` in `SPARK_OPTS`, is this result expected?

After checking the file `/usr/local/spark/conf/spark-env.sh.template`, I used the variable `SPARK_DRIVER_MEMORY` and it did work as I expected.

### PR DESCRIPTION
**Pull request by parente**
Should fix #169

### CODE REVIEW

**Comment by parente** [comment]
@Lull3rskat3r or @lbustelo, can one of you give the README a review and see if it's correct and makes sense?

**Comment by lbustelo** [comment]
@parente I was doing this but waiting for dev7. Corey had a fix I wanted to get in before all the updating.

**Comment by parente** [comment]
@lbustelo OK. Will wait for yours. Grab whatever makes sense out of the README from this one.

The travis failure is from my forgetting to update the SHA for the spark tarball.

**Comment by lbustelo** [comment]
Cool... I'll try to get all in place by this PM

**Pull request closed without merging**
