### PR TITLE
add cm-super

### PR DESCRIPTION
**Pull request by mpmdean**
Aims to address issue #1160 -- an error when using latex labels in matplotlib inside scipy-notebook.

### CODE REVIEW

**Review by romainx — CHANGES_REQUESTED** [review]
Hello @mpmdean ,

Thank you for this proposal. I've a question regarding the location of the installation of this package.
I guess it's useful not only for `matplotlib` plots and this is the reason why you installed it in `minimal-notebook` with other `nbconvert` dependencies -- and it make sense in this case. In the other case, if it's only useful for `matplotlib` plots we should consider installing it in the `scipy-notebook` since this installation adds ~50 MB to the image size.

Then It will be nice to add a test at the following location https://github.com/jupyter/docker-stacks/blob/612aa5710bf9f9394a6b108cda6cbbc88f41f924/scipy-notebook/test/test_matplotlib.py#L12

Since you have already a snippet of code that reproduces the issue, it's worth adding it to the test cases. Let me know if you have trouble adding it.
Finally could you add a comment near the package in order to indicate its purpose?

Note: The build is failing due to a previous issue fixed in the PR #1158. You can fix the build by rebasing your branch with the origin/master.

Many thanks.

**Comment by mpmdean** [comment]
Hi @romainx 

It's a bit marginal whether the change belongs in ``minimal-notebook`` or ``scipy-notebook``. 

I assumed that it would probably be helpful for ``nbconvert`` since that uses latex, but having looked in more detail one probably needs to have written a custom template and added the computer modern font. For matplotlib, however, cm-super is a optional dependency and one can run into problems relatively easily and unexpectedly.

This package:
https://phonopy.github.io/phonopy/
assumes cm-super is installed for example. 

Maybe  ``scipy-notebook` is a better location? Please let me know what you think.

**Comment by romainx** [comment]
Hello @mpmdean,

Thanks for the precision. I'm sorry but I do not know so much about `nbconvert`. Maybe if we are hesitating between the two location let's add it in `scipy-notebook`

- because we know it is useful
- because it will avoid increasing the size of all images

Is it Ok for you?

If so, could you also consider add your test case like it's already done here for `matplotlib`?

https://github.com/jupyter/docker-stacks/blob/612aa5710bf9f9394a6b108cda6cbbc88f41f924/scipy-notebook/test/test_matplotlib.py#L12

If you are not confortable with that, please let me know I will perform it  in a follow-on PR.

Best.

**Comment by mpmdean** [comment]
@romainx 

That rebase seems to have created a total mess. I think I'll close this and create a new PR of the updated master.

**Comment by mpmdean** [comment]
Changes continue in #1169

**Pull request closed without merging**
