### PR TITLE
Start using matrix in reuseable workflows directly

### PR DESCRIPTION
**Pull request by mathbunnyru**
## Checklist (especially for first-time contributors)

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@consideRatio @manics @minrk
It is now possible to use a matrix strategy with a reusable workflow.
https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-a-matrix-strategy-with-a-reusable-workflow

**Comment by consideRatio** [comment]
> It is now possible to use a matrix strategy with a reusable workflow.
https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-a-matrix-strategy-with-a-reusable-workflow

Ping @sgibson91 who often pushes the limits of what is possible with github actions

**Review by consideRatio — APPROVED** [review]
Beautiful! :tada: :heart: :sunflower:

Small detail, there was an outdated description on line 1 in the merge-tags workflow - referencing "images"

**Comment by mathbunnyru** [comment]
> Beautiful! 🎉 ❤️ 🌻
> 
> Small detail, there was an outdated description on line 1 in the merge-tags workflow - referencing "images"

In this case I think that it's actually correct, because it downloads 2 images: one for x86_64 and one for aarch64.

**Pull request merged**
