### PR TITLE
Add and install from the r channel with conda

### PR DESCRIPTION
**Pull request by jakirkham**
Combines the conda config update line and the installation of R packages into the same `RUN` command.

### CODE REVIEW

**Comment by parente** [comment]
Fine by me. Is the benefit that we have fewer layers?

**Comment by jakirkham** [comment]
I thought it might be nice to have the R steps be one layer.

**Comment by parente** [comment]
:+1:

**Comment by jakirkham** [comment]
Sorry, should have waited for your response.

**Pull request merged**
