### PR TITLE
Update Dockerfile to R 3.6.2

### PR DESCRIPTION
**Pull request by xiaodaigh**

### CODE REVIEW

**Comment by romainx** [comment]
In the PR #1021 I have also bumped the R version in `r-notebook`. If you could have a look there is some additional packages to update. It could be interesting to group all the update in a single PR.

Thanks a lot.

**Comment by xiaodaigh** [comment]
Hopefully can be in soon as moe it's basically unusable because some packages like stringi are not installable

**Comment by romainx** [comment]
:-) Please also note that there is an initiative (#693) in progress to deprecate this notebook.

**Comment by parente** [comment]
Thanks for the PR @xiaodaigh. @romainx has fixed this in #1021 which is building now on Docker Hub.

**Pull request closed without merging**
